-- ╔══════════════════════════════════════════════════════════════════════╗
-- ║  seed.sql · catálogo completo para desarrollo local                   ║
-- ╚══════════════════════════════════════════════════════════════════════╝
-- GENERADO por scripts/gen-seed-sql.mjs — no editar a mano.
-- Se ejecuta con `supabase db reset` (después de las migraciones).
-- Fuente: src/content/*.json. Para staging/producción usar `npm run seed`.
-- rarities / finishes / store_config los siembra la migración 0001. Las
-- categorías salen de src/content/categories.json (además de las 3 base de
-- la migración) para soportar categorías nuevas en dev local.

insert into public.categories (slug, name, sort_order) values
  ('fortnite', 'Fortnite', 1),
  ('meme', 'Memes', 2),
  ('dev', 'Dev / Tech', 3),
  ('gatos', 'Gatos', 4),
  ('frases', 'Frases', 5)
on conflict (slug) do update set name = excluded.name, sort_order = excluded.sort_order;

insert into public.stickers (slug, name, image_url, category_id, rarity_id, rarity_label, price, sort_order) values
  ('fortnite-john-wick', 'John Wick', 'https://fortnite.gg/img/x/sprites/icons/T_Icon_Reload_FillerGrunt_icon_L.webp', (select id from public.categories where slug = 'fortnite'), (select id from public.rarities where slug = 'mythic'), 'Mítico', 1, 0),
  ('fortnite-batman', 'Batman', 'https://fortnite.gg/img/x/sprites/icons/T_Icon_BR_FossilMeal_Default_L.webp', (select id from public.categories where slug = 'fortnite'), (select id from public.rarities where slug = 'mythic'), 'Mítico', 1, 1),
  ('fortnite-vini-jr', 'Vini Jr.', 'https://fortnite.gg/img/x/sprites/icons/T_Icon_BR_CokeParmesan_Default_L.webp', (select id from public.categories where slug = 'fortnite'), (select id from public.rarities where slug = 'mythic'), 'Mítico', 1, 2),
  ('fortnite-burnt-peanut', 'Burnt Peanut', 'https://fortnite.gg/img/x/sprites/icons/T_Icon_BR_Creature_Sprite_BurntPeanut_ui_L.webp', (select id from public.categories where slug = 'fortnite'), (select id from public.rarities where slug = 'mythic'), 'Mítico', 1, 3),
  ('fortnite-zero-point', 'Zero Point', 'https://fortnite.gg/img/x/sprites/icons/T_Icon_BR_Creature_Sprite_ZeroPoint_ui_L.webp', (select id from public.categories where slug = 'fortnite'), (select id from public.rarities where slug = 'mythic'), 'Mítico', 1, 4),
  ('fortnite-grim', 'Grim', 'https://fortnite.gg/img/x/sprites/icons/T_Icon_BR_GrimReaper_Default_L.webp', (select id from public.categories where slug = 'fortnite'), (select id from public.rarities where slug = 'mythic'), 'Mítico', 1, 5),
  ('fortnite-ironmouse', 'Ironmouse', 'https://fortnite.gg/img/x/sprites/icons/T_Icon_BR_PedicureAntacid_L.webp', (select id from public.categories where slug = 'fortnite'), (select id from public.rarities where slug = 'mythic'), 'Mítico', 1, 6),
  ('fortnite-pollo', 'Pollo', 'https://fortnite.gg/img/x/sprites/icons/T_Icon_BR_CompanyStargazer_Default_L.webp', (select id from public.categories where slug = 'fortnite'), (select id from public.rarities where slug = 'mythic'), 'Mítico', 1, 7),
  ('fortnite-dream', 'Dream', 'https://fortnite.gg/img/x/sprites/icons/T_Icon_BR_Creature_Sprite_Sleepy_ui_L.webp', (select id from public.categories where slug = 'fortnite'), (select id from public.rarities where slug = 'legendary'), 'Legendario', 1, 8),
  ('fortnite-punk', 'Punk', 'https://fortnite.gg/img/x/sprites/icons/T_Icon_BR_Creature_Sprite_Punk_ui_L.webp', (select id from public.categories where slug = 'fortnite'), (select id from public.rarities where slug = 'legendary'), 'Legendario', 1, 9),
  ('fortnite-boss', 'Boss', 'https://fortnite.gg/img/x/sprites/icons/T_Icon_BR_Creature_Sprite_Boss_ui_L.webp', (select id from public.categories where slug = 'fortnite'), (select id from public.rarities where slug = 'legendary'), 'Legendario', 1, 10),
  ('fortnite-seven', 'Seven', 'https://fortnite.gg/img/x/sprites/icons/T_Icon_BR_Creature_Sprite_Seven_ui_L.webp', (select id from public.categories where slug = 'fortnite'), (select id from public.rarities where slug = 'legendary'), 'Legendario', 1, 11),
  ('fortnite-llama', 'Llama', 'https://fortnite.gg/img/x/sprites/icons/T_Icon_BR_Creature_Sprite_Llama_ui_L.webp', (select id from public.categories where slug = 'fortnite'), (select id from public.rarities where slug = 'legendary'), 'Legendario', 1, 12),
  ('fortnite-peely', 'Peely', 'https://fortnite.gg/img/x/sprites/icons/T_Icon_BR_Creature_Sprite_Peely_ui_L.webp', (select id from public.categories where slug = 'fortnite'), (select id from public.rarities where slug = 'legendary'), 'Legendario', 1, 13),
  ('fortnite-duck', 'Duck', 'https://fortnite.gg/img/x/sprites/icons/T_Icon_BR_Duck_Default_L.webp', (select id from public.categories where slug = 'fortnite'), (select id from public.rarities where slug = 'epic'), 'Épico', 1, 14),
  ('fortnite-ghost', 'Ghost', 'https://fortnite.gg/img/x/sprites/icons/T_Icon_BR_Creature_Sprite_Ghost_Unvault_L.webp', (select id from public.categories where slug = 'fortnite'), (select id from public.rarities where slug = 'epic'), 'Épico', 1, 15),
  ('fortnite-demon', 'Demon', 'https://fortnite.gg/img/x/sprites/icons/T_Icon_BR_RedDemon_Default_L.webp', (select id from public.categories where slug = 'fortnite'), (select id from public.rarities where slug = 'epic'), 'Épico', 1, 16),
  ('fortnite-king', 'King', 'https://fortnite.gg/img/x/sprites/icons/T_Icon_BR_Creature_Sprite_King_ui_L.webp', (select id from public.categories where slug = 'fortnite'), (select id from public.rarities where slug = 'epic'), 'Épico', 1, 17),
  ('fortnite-striker', 'Striker', 'https://fortnite.gg/img/x/sprites/icons/T_Icon_BR_Creature_Sprite_Soccer_ui_L.webp', (select id from public.categories where slug = 'fortnite'), (select id from public.rarities where slug = 'epic'), 'Épico', 1, 18),
  ('fortnite-aura', 'Aura', 'https://fortnite.gg/img/x/sprites/icons/T_Icon_BR_Creature_Sprite_Drifter_ui_L.webp', (select id from public.categories where slug = 'fortnite'), (select id from public.rarities where slug = 'epic'), 'Épico', 1, 19),
  ('fortnite-water', 'Water', 'https://fortnite.gg/img/x/sprites/icons/T_Icon_BR_Creature_Sprite_Water_Unvault_Ch7S3_ui_L.webp', (select id from public.categories where slug = 'fortnite'), (select id from public.rarities where slug = 'rare'), 'Raro', 1, 20),
  ('fortnite-earth', 'Earth', 'https://fortnite.gg/img/x/sprites/icons/T_Icon_BR_Creature_Sprite_Earth_Ch7S3_UI_L.webp', (select id from public.categories where slug = 'fortnite'), (select id from public.rarities where slug = 'rare'), 'Raro', 1, 21),
  ('fortnite-fire', 'Fire', 'https://fortnite.gg/img/x/sprites/icons/T_Icon_BR_Creature_Sprite_Fire_Unvault_Ch7S3_ui_L.webp', (select id from public.categories where slug = 'fortnite'), (select id from public.rarities where slug = 'rare'), 'Raro', 1, 22),
  ('fortnite-fishy', 'Fishy', 'https://fortnite.gg/img/x/sprites/icons/T_Icon_BR_Creature_Sprite_Fishy_ui_L.webp', (select id from public.categories where slug = 'fortnite'), (select id from public.rarities where slug = 'rare'), 'Raro', 1, 23),
  ('fortnite-air', 'Air', 'https://fortnite.gg/img/x/sprites/icons/T_Icon_BR_Air_Default_L.webp', (select id from public.categories where slug = 'fortnite'), (select id from public.rarities where slug = 'rare'), 'Raro', 1, 24),
  ('fortnite-cube-batman', 'Cube Batman', 'https://fortnite.gg/img/x/sprites/icons/T_Icon_BR_FossilMeal_Cube_L.webp', (select id from public.categories where slug = 'fortnite'), (select id from public.rarities where slug = 'special'), 'Special', 1, 25),
  ('fortnite-gold-batman', 'Gold Batman', 'https://fortnite.gg/img/x/sprites/icons/T_Icon_BR_FossilMeal_Gold_L.webp', (select id from public.categories where slug = 'fortnite'), (select id from public.rarities where slug = 'special'), 'Special', 1, 26),
  ('fortnite-gummy-batman', 'Gummy Batman', 'https://fortnite.gg/img/x/sprites/icons/T_Icon_BR_FossilMeal_Candy_L.webp', (select id from public.categories where slug = 'fortnite'), (select id from public.rarities where slug = 'special'), 'Special', 1, 27),
  ('fortnite-galaxy-batman', 'Galaxy Batman', 'https://fortnite.gg/img/x/sprites/icons/T_Icon_BR_FossilMeal_Galaxy_L.webp', (select id from public.categories where slug = 'fortnite'), (select id from public.rarities where slug = 'special'), 'Special', 1, 28),
  ('fortnite-holofoil-batman', 'Holofoil Batman', 'https://fortnite.gg/img/x/sprites/icons/T_Icon_BR_FossilMeal_Holofoil_L.webp', (select id from public.categories where slug = 'fortnite'), (select id from public.rarities where slug = 'special'), 'Special', 1, 29),
  ('fortnite-gold-water', 'Gold Water', 'https://fortnite.gg/img/x/sprites/icons/T_Icon_BR_Creature_Sprite_Water_Gold_ui_L.webp', (select id from public.categories where slug = 'fortnite'), (select id from public.rarities where slug = 'special'), 'Special', 1, 30),
  ('fortnite-quack-water', 'Quack Water', 'https://fortnite.gg/img/x/sprites/icons/T_Icon_BR_Creature_Sprite_Water_Quack_ui_L.webp', (select id from public.categories where slug = 'fortnite'), (select id from public.rarities where slug = 'special'), 'Special', 1, 31),
  ('fortnite-gummy-water', 'Gummy Water', 'https://fortnite.gg/img/x/sprites/icons/T_Icon_BR_Creature_Sprite_Water_Candy_ui_L.webp', (select id from public.categories where slug = 'fortnite'), (select id from public.rarities where slug = 'special'), 'Special', 1, 32),
  ('fortnite-galaxy-water', 'Galaxy Water', 'https://fortnite.gg/img/x/sprites/icons/T_Icon_BR_Creature_Sprite_Water_Galaxy_ui_L.webp', (select id from public.categories where slug = 'fortnite'), (select id from public.rarities where slug = 'special'), 'Special', 1, 33),
  ('fortnite-gem-water', 'Gem Water', 'https://fortnite.gg/img/x/sprites/icons/T_Icon_BR_Creature_Sprite_Water_Gem_ui_L.webp', (select id from public.categories where slug = 'fortnite'), (select id from public.rarities where slug = 'special'), 'Special', 1, 34),
  ('fortnite-holofoil-water', 'Holofoil Water', 'https://fortnite.gg/img/x/sprites/icons/T_Icon_BR_Creature_Sprite_Water_Holofoil_ui_L.webp', (select id from public.categories where slug = 'fortnite'), (select id from public.rarities where slug = 'special'), 'Special', 1, 35),
  ('fortnite-cube-earth', 'Cube Earth', 'https://fortnite.gg/img/x/sprites/icons/T_Icon_BR_Creature_Sprite_Earth_Cube_ui_L.webp', (select id from public.categories where slug = 'fortnite'), (select id from public.rarities where slug = 'special'), 'Special', 1, 36),
  ('fortnite-gold-earth', 'Gold Earth', 'https://fortnite.gg/img/x/sprites/icons/T_Icon_BR_Creature_Sprite_Earth_Gold_ui_L.webp', (select id from public.categories where slug = 'fortnite'), (select id from public.rarities where slug = 'special'), 'Special', 1, 37),
  ('fortnite-quack-earth', 'Quack Earth', 'https://fortnite.gg/img/x/sprites/icons/T_Icon_BR_Creature_Sprite_Earth_Quack_ui_L.webp', (select id from public.categories where slug = 'fortnite'), (select id from public.rarities where slug = 'special'), 'Special', 1, 38),
  ('fortnite-gummy-earth', 'Gummy Earth', 'https://fortnite.gg/img/x/sprites/icons/T_Icon_BR_Creature_Sprite_Earth_Candy_ui_L.webp', (select id from public.categories where slug = 'fortnite'), (select id from public.rarities where slug = 'special'), 'Special', 1, 39),
  ('fortnite-galaxy-earth', 'Galaxy Earth', 'https://fortnite.gg/img/x/sprites/icons/T_Icon_BR_Creature_Sprite_Earth_Galaxy_ui_L.webp', (select id from public.categories where slug = 'fortnite'), (select id from public.rarities where slug = 'special'), 'Special', 1, 40),
  ('fortnite-gem-earth', 'Gem Earth', 'https://fortnite.gg/img/x/sprites/icons/T_Icon_BR_Creature_Sprite_Earth_Gem_ui_L.webp', (select id from public.categories where slug = 'fortnite'), (select id from public.rarities where slug = 'special'), 'Special', 1, 41),
  ('fortnite-cube-fire', 'Cube Fire', 'https://fortnite.gg/img/x/sprites/icons/T_Icon_BR_Creature_Sprite_Fire_Cube_ui_L.webp', (select id from public.categories where slug = 'fortnite'), (select id from public.rarities where slug = 'special'), 'Special', 1, 42),
  ('fortnite-gold-fire', 'Gold Fire', 'https://fortnite.gg/img/x/sprites/icons/T_Icon_BR_Creature_Sprite_Fire_Gold_ui_L.webp', (select id from public.categories where slug = 'fortnite'), (select id from public.rarities where slug = 'special'), 'Special', 1, 43),
  ('fortnite-quack-fire', 'Quack Fire', 'https://fortnite.gg/img/x/sprites/icons/T_Icon_BR_Creature_Sprite_Fire_Quack_ui_L.webp', (select id from public.categories where slug = 'fortnite'), (select id from public.rarities where slug = 'special'), 'Special', 1, 44),
  ('fortnite-gummy-fire', 'Gummy Fire', 'https://fortnite.gg/img/x/sprites/icons/T_Icon_BR_Creature_Sprite_Fire_Candy_ui_L.webp', (select id from public.categories where slug = 'fortnite'), (select id from public.rarities where slug = 'special'), 'Special', 1, 45),
  ('fortnite-galaxy-fire', 'Galaxy Fire', 'https://fortnite.gg/img/x/sprites/icons/T_Icon_BR_Creature_Sprite_Fire_Galaxy_ui_L.webp', (select id from public.categories where slug = 'fortnite'), (select id from public.rarities where slug = 'special'), 'Special', 1, 46),
  ('fortnite-holofoil-fire', 'Holofoil Fire', 'https://fortnite.gg/img/x/sprites/icons/T_Icon_BR_Creature_Sprite_Fire_Holofoil_ui_L.webp', (select id from public.categories where slug = 'fortnite'), (select id from public.rarities where slug = 'special'), 'Special', 1, 47),
  ('fortnite-gold-duck', 'Gold Duck', 'https://fortnite.gg/img/x/sprites/icons/T_Icon_BR_Duck_Gold_L.webp', (select id from public.categories where slug = 'fortnite'), (select id from public.rarities where slug = 'special'), 'Special', 1, 48),
  ('fortnite-gummy-duck', 'Gummy Duck', 'https://fortnite.gg/img/x/sprites/icons/T_Icon_BR_Duck_Candy_L.webp', (select id from public.categories where slug = 'fortnite'), (select id from public.rarities where slug = 'special'), 'Special', 1, 49),
  ('fortnite-galaxy-duck', 'Galaxy Duck', 'https://fortnite.gg/img/x/sprites/icons/T_Icon_BR_Duck_Galaxy_L.webp', (select id from public.categories where slug = 'fortnite'), (select id from public.rarities where slug = 'special'), 'Special', 1, 50),
  ('fortnite-gem-duck', 'Gem Duck', 'https://fortnite.gg/img/x/sprites/icons/T_Icon_BR_Duck_Gem_L.webp', (select id from public.categories where slug = 'fortnite'), (select id from public.rarities where slug = 'special'), 'Special', 1, 51),
  ('fortnite-gold-ghost', 'Gold Ghost', 'https://fortnite.gg/img/x/sprites/icons/T_Icon_BR_Creature_Sprite_Ghost_Gold_L.webp', (select id from public.categories where slug = 'fortnite'), (select id from public.rarities where slug = 'special'), 'Special', 1, 52),
  ('fortnite-gummy-ghost', 'Gummy Ghost', 'https://fortnite.gg/img/x/sprites/icons/T_Icon_BR_Creature_Sprite_Ghost_Candy_L.webp', (select id from public.categories where slug = 'fortnite'), (select id from public.rarities where slug = 'special'), 'Special', 1, 53),
  ('fortnite-galaxy-ghost', 'Galaxy Ghost', 'https://fortnite.gg/img/x/sprites/icons/T_Icon_BR_Creature_Sprite_Ghost_Galaxy_L.webp', (select id from public.categories where slug = 'fortnite'), (select id from public.rarities where slug = 'special'), 'Special', 1, 54),
  ('fortnite-holofoil-ghost', 'Holofoil Ghost', 'https://fortnite.gg/img/x/sprites/icons/T_Icon_BR_Creature_Sprite_Ghost_Holo_L.webp', (select id from public.categories where slug = 'fortnite'), (select id from public.rarities where slug = 'special'), 'Special', 1, 55),
  ('fortnite-cube-dream', 'Cube Dream', 'https://fortnite.gg/img/x/sprites/icons/T_Icon_BR_Creature_Sprite_Sleepy_Cube_ui_L.webp', (select id from public.categories where slug = 'fortnite'), (select id from public.rarities where slug = 'special'), 'Special', 1, 56),
  ('fortnite-gold-dream', 'Gold Dream', 'https://fortnite.gg/img/x/sprites/icons/T_Icon_BR_Creature_Sprite_Sleepy_Gold_ui_L.webp', (select id from public.categories where slug = 'fortnite'), (select id from public.rarities where slug = 'special'), 'Special', 1, 57),
  ('fortnite-gummy-dream', 'Gummy Dream', 'https://fortnite.gg/img/x/sprites/icons/T_Icon_BR_Creature_Sprite_Sleepy_Candy_ui_L.webp', (select id from public.categories where slug = 'fortnite'), (select id from public.rarities where slug = 'special'), 'Special', 1, 58),
  ('fortnite-galaxy-dream', 'Galaxy Dream', 'https://fortnite.gg/img/x/sprites/icons/T_Icon_BR_Creature_Sprite_Sleepy_Galaxy_ui_L.webp', (select id from public.categories where slug = 'fortnite'), (select id from public.rarities where slug = 'special'), 'Special', 1, 59),
  ('fortnite-gold-demon', 'Gold Demon', 'https://fortnite.gg/img/x/sprites/icons/T_Icon_BR_RedDemon_Gold_L.webp', (select id from public.categories where slug = 'fortnite'), (select id from public.rarities where slug = 'special'), 'Special', 1, 60),
  ('fortnite-gummy-demon', 'Gummy Demon', 'https://fortnite.gg/img/x/sprites/icons/T_Icon_BR_RedDemon_Candy_L.webp', (select id from public.categories where slug = 'fortnite'), (select id from public.rarities where slug = 'special'), 'Special', 1, 61),
  ('fortnite-galaxy-demon', 'Galaxy Demon', 'https://fortnite.gg/img/x/sprites/icons/T_Icon_BR_RedDemon_Galaxy_L.webp', (select id from public.categories where slug = 'fortnite'), (select id from public.rarities where slug = 'special'), 'Special', 1, 62),
  ('fortnite-gem-demon', 'Gem Demon', 'https://fortnite.gg/img/x/sprites/icons/T_Icon_BR_RedDemon_Gem_L.webp', (select id from public.categories where slug = 'fortnite'), (select id from public.rarities where slug = 'special'), 'Special', 1, 63),
  ('fortnite-cube-punk', 'Cube Punk', 'https://fortnite.gg/img/x/sprites/icons/T_Icon_BR_Creature_Sprite_Punk_Cube_ui_L.webp', (select id from public.categories where slug = 'fortnite'), (select id from public.rarities where slug = 'special'), 'Special', 1, 64),
  ('fortnite-gold-punk', 'Gold Punk', 'https://fortnite.gg/img/x/sprites/icons/T_Icon_BR_Creature_Sprite_Punk_Gold_ui_L.webp', (select id from public.categories where slug = 'fortnite'), (select id from public.rarities where slug = 'special'), 'Special', 1, 65),
  ('fortnite-gummy-punk', 'Gummy Punk', 'https://fortnite.gg/img/x/sprites/icons/T_Icon_BR_Creature_Sprite_Punk_Candy_ui_L.webp', (select id from public.categories where slug = 'fortnite'), (select id from public.rarities where slug = 'special'), 'Special', 1, 66),
  ('fortnite-galaxy-punk', 'Galaxy Punk', 'https://fortnite.gg/img/x/sprites/icons/T_Icon_BR_Creature_Sprite_Punk_Galaxy_ui_L.webp', (select id from public.categories where slug = 'fortnite'), (select id from public.rarities where slug = 'special'), 'Special', 1, 67),
  ('fortnite-gold-king', 'Gold King', 'https://fortnite.gg/img/x/sprites/icons/T_Icon_BR_Creature_Sprite_King_Gold_ui_L.webp', (select id from public.categories where slug = 'fortnite'), (select id from public.rarities where slug = 'special'), 'Special', 1, 68),
  ('fortnite-gummy-king', 'Gummy King', 'https://fortnite.gg/img/x/sprites/icons/T_Icon_BR_Creature_Sprite_King_Candy_ui_L.webp', (select id from public.categories where slug = 'fortnite'), (select id from public.rarities where slug = 'special'), 'Special', 1, 69),
  ('fortnite-galaxy-king', 'Galaxy King', 'https://fortnite.gg/img/x/sprites/icons/T_Icon_BR_Creature_Sprite_King_Galaxy_ui_L.webp', (select id from public.categories where slug = 'fortnite'), (select id from public.rarities where slug = 'special'), 'Special', 1, 70),
  ('fortnite-holofoil-king', 'Holofoil King', 'https://fortnite.gg/img/x/sprites/icons/T_Icon_BR_Creature_Sprite_King_Holofoil_ui_L.webp', (select id from public.categories where slug = 'fortnite'), (select id from public.rarities where slug = 'special'), 'Special', 1, 71),
  ('fortnite-cube-zero-point', 'Cube Zero Point', 'https://fortnite.gg/img/x/sprites/icons/T_Icon_BR_Creature_Sprite_ZeroPoint_Cube_ui_L.webp', (select id from public.categories where slug = 'fortnite'), (select id from public.rarities where slug = 'special'), 'Special', 1, 72),
  ('fortnite-gold-zero-point', 'Gold Zero Point', 'https://fortnite.gg/img/x/sprites/icons/T_Icon_BR_Creature_Sprite_ZeroPoint_Gold_ui_L.webp', (select id from public.categories where slug = 'fortnite'), (select id from public.rarities where slug = 'special'), 'Special', 1, 73),
  ('fortnite-quack-zero-point', 'Quack Zero Point', 'https://fortnite.gg/img/x/sprites/icons/T_Icon_BR_Creature_Sprite_ZeroPoint_Quack_ui_L.webp', (select id from public.categories where slug = 'fortnite'), (select id from public.rarities where slug = 'special'), 'Special', 1, 74),
  ('fortnite-gummy-zero-point', 'Gummy Zero Point', 'https://fortnite.gg/img/x/sprites/icons/T_Icon_BR_Creature_Sprite_ZeroPoint_Candy_ui_L.webp', (select id from public.categories where slug = 'fortnite'), (select id from public.rarities where slug = 'special'), 'Special', 1, 75),
  ('fortnite-galaxy-zero-point', 'Galaxy Zero Point', 'https://fortnite.gg/img/x/sprites/icons/T_Icon_BR_Creature_Sprite_ZeroPoint_Galaxy_ui_L.webp', (select id from public.categories where slug = 'fortnite'), (select id from public.rarities where slug = 'special'), 'Special', 1, 76),
  ('fortnite-gem-zero-point', 'Gem Zero Point', 'https://fortnite.gg/img/x/sprites/icons/T_Icon_BR_Creature_Sprite_ZeroPoint_Gem_ui_L.webp', (select id from public.categories where slug = 'fortnite'), (select id from public.rarities where slug = 'special'), 'Special', 1, 77),
  ('fortnite-holofoil-zero-point', 'Holofoil Zero Point', 'https://fortnite.gg/img/x/sprites/icons/T_Icon_BR_Creature_Sprite_ZeroPoint_Holofoil_ui_L.webp', (select id from public.categories where slug = 'fortnite'), (select id from public.rarities where slug = 'special'), 'Special', 1, 78),
  ('fortnite-cube-fishy', 'Cube Fishy', 'https://fortnite.gg/img/x/sprites/icons/T_Icon_BR_Creature_Sprite_Fishy_Cube_L.webp', (select id from public.categories where slug = 'fortnite'), (select id from public.rarities where slug = 'special'), 'Special', 1, 79),
  ('fortnite-gold-fishy', 'Gold Fishy', 'https://fortnite.gg/img/x/sprites/icons/T_Icon_BR_Creature_Sprite_Fishy_Gold_ui_L.webp', (select id from public.categories where slug = 'fortnite'), (select id from public.rarities where slug = 'special'), 'Special', 1, 80),
  ('fortnite-gummy-fishy', 'Gummy Fishy', 'https://fortnite.gg/img/x/sprites/icons/T_Icon_BR_Creature_Sprite_Fishy_Candy_ui_L.webp', (select id from public.categories where slug = 'fortnite'), (select id from public.rarities where slug = 'special'), 'Special', 1, 81),
  ('fortnite-galaxy-fishy', 'Galaxy Fishy', 'https://fortnite.gg/img/x/sprites/icons/T_Icon_BR_Creature_Sprite_Fishy_Galaxy_ui_L.webp', (select id from public.categories where slug = 'fortnite'), (select id from public.rarities where slug = 'special'), 'Special', 1, 82),
  ('fortnite-gold-striker', 'Gold Striker', 'https://fortnite.gg/img/x/sprites/icons/T_Icon_BR_Creature_Sprite_Soccer_Gold_L.webp', (select id from public.categories where slug = 'fortnite'), (select id from public.rarities where slug = 'special'), 'Special', 1, 83),
  ('fortnite-gummy-striker', 'Gummy Striker', 'https://fortnite.gg/img/x/sprites/icons/T_Icon_BR_Creature_Sprite_Soccer_Candy_L.webp', (select id from public.categories where slug = 'fortnite'), (select id from public.rarities where slug = 'special'), 'Special', 1, 84),
  ('fortnite-galaxy-striker', 'Galaxy Striker', 'https://fortnite.gg/img/x/sprites/icons/T_Icon_BR_Creature_Sprite_Soccer_Galaxy_L.webp', (select id from public.categories where slug = 'fortnite'), (select id from public.rarities where slug = 'special'), 'Special', 1, 85),
  ('fortnite-holofoil-striker', 'Holofoil Striker', 'https://fortnite.gg/img/x/sprites/icons/T_Icon_BR_Creature_Sprite_Soccer_Holofoil_L.webp', (select id from public.categories where slug = 'fortnite'), (select id from public.rarities where slug = 'special'), 'Special', 1, 86),
  ('fortnite-gold-aura', 'Gold Aura', 'https://fortnite.gg/img/x/sprites/icons/T_Icon_BR_Creature_Sprite_Drifter_Gold_ui_L.webp', (select id from public.categories where slug = 'fortnite'), (select id from public.rarities where slug = 'special'), 'Special', 1, 87),
  ('fortnite-gummy-aura', 'Gummy Aura', 'https://fortnite.gg/img/x/sprites/icons/T_Icon_BR_Creature_Sprite_Drifter_Candy_ui_L.webp', (select id from public.categories where slug = 'fortnite'), (select id from public.rarities where slug = 'special'), 'Special', 1, 88),
  ('fortnite-galaxy-aura', 'Galaxy Aura', 'https://fortnite.gg/img/x/sprites/icons/T_Icon_BR_Creature_Sprite_Drifter_Galaxy_ui_L.webp', (select id from public.categories where slug = 'fortnite'), (select id from public.rarities where slug = 'special'), 'Special', 1, 89),
  ('fortnite-gem-aura', 'Gem Aura', 'https://fortnite.gg/img/x/sprites/icons/T_Icon_BR_Creature_Sprite_Drifter_Gem_ui_L.webp', (select id from public.categories where slug = 'fortnite'), (select id from public.rarities where slug = 'special'), 'Special', 1, 90),
  ('fortnite-cube-boss', 'Cube Boss', 'https://fortnite.gg/img/x/sprites/icons/T_Icon_BR_Creature_Sprite_Boss_Cube_ui_L.webp', (select id from public.categories where slug = 'fortnite'), (select id from public.rarities where slug = 'special'), 'Special', 1, 91),
  ('fortnite-gold-boss', 'Gold Boss', 'https://fortnite.gg/img/x/sprites/icons/T_Icon_BR_Creature_Sprite_Boss_Gold_ui_L.webp', (select id from public.categories where slug = 'fortnite'), (select id from public.rarities where slug = 'special'), 'Special', 1, 92),
  ('fortnite-gummy-boss', 'Gummy Boss', 'https://fortnite.gg/img/x/sprites/icons/T_Icon_BR_Creature_Sprite_Boss_Candy_ui_L.webp', (select id from public.categories where slug = 'fortnite'), (select id from public.rarities where slug = 'special'), 'Special', 1, 93),
  ('fortnite-galaxy-boss', 'Galaxy Boss', 'https://fortnite.gg/img/x/sprites/icons/T_Icon_BR_Creature_Sprite_Boss_Galaxy_ui_L.webp', (select id from public.categories where slug = 'fortnite'), (select id from public.rarities where slug = 'special'), 'Special', 1, 94),
  ('fortnite-cube-grim', 'Cube Grim', 'https://fortnite.gg/img/x/sprites/icons/T_Icon_BR_GrimReaper_Cube_L.webp', (select id from public.categories where slug = 'fortnite'), (select id from public.rarities where slug = 'special'), 'Special', 1, 95),
  ('fortnite-gold-grim', 'Gold Grim', 'https://fortnite.gg/img/x/sprites/icons/T_Icon_BR_GrimReaper_Gold_L.webp', (select id from public.categories where slug = 'fortnite'), (select id from public.rarities where slug = 'special'), 'Special', 1, 96),
  ('fortnite-gummy-grim', 'Gummy Grim', 'https://fortnite.gg/img/x/sprites/icons/T_Icon_BR_GrimReaper_Candy_L.webp', (select id from public.categories where slug = 'fortnite'), (select id from public.rarities where slug = 'special'), 'Special', 1, 97),
  ('fortnite-galaxy-grim', 'Galaxy Grim', 'https://fortnite.gg/img/x/sprites/icons/T_Icon_BR_GrimReaper_Galaxy_L.webp', (select id from public.categories where slug = 'fortnite'), (select id from public.rarities where slug = 'special'), 'Special', 1, 98),
  ('fortnite-gem-grim', 'Gem Grim', 'https://fortnite.gg/img/x/sprites/icons/T_Icon_BR_GrimReaper_Gem_L.webp', (select id from public.categories where slug = 'fortnite'), (select id from public.rarities where slug = 'special'), 'Special', 1, 99),
  ('fortnite-holofoil-grim', 'Holofoil Grim', 'https://fortnite.gg/img/x/sprites/icons/T_Icon_BR_GrimReaper_Holofoil_L.webp', (select id from public.categories where slug = 'fortnite'), (select id from public.rarities where slug = 'special'), 'Special', 1, 100),
  ('fortnite-gold-air', 'Gold Air', 'https://fortnite.gg/img/x/sprites/icons/T_Icon_BR_Air_Gold_L.webp', (select id from public.categories where slug = 'fortnite'), (select id from public.rarities where slug = 'special'), 'Special', 1, 101),
  ('fortnite-gummy-air', 'Gummy Air', 'https://fortnite.gg/img/x/sprites/icons/T_Icon_BR_Air_Candy_L.webp', (select id from public.categories where slug = 'fortnite'), (select id from public.rarities where slug = 'special'), 'Special', 1, 102),
  ('fortnite-galaxy-air', 'Galaxy Air', 'https://fortnite.gg/img/x/sprites/icons/T_Icon_BR_Air_Galaxy_L.webp', (select id from public.categories where slug = 'fortnite'), (select id from public.rarities where slug = 'special'), 'Special', 1, 103),
  ('fortnite-holofoil-air', 'Holofoil Air', 'https://fortnite.gg/img/x/sprites/icons/T_Icon_BR_Air_Holo_L.webp', (select id from public.categories where slug = 'fortnite'), (select id from public.rarities where slug = 'special'), 'Special', 1, 104),
  ('fortnite-gold-seven', 'Gold Seven', 'https://fortnite.gg/img/x/sprites/icons/T_Icon_BR_Creature_Sprite_Seven_Gold_ui_L.webp', (select id from public.categories where slug = 'fortnite'), (select id from public.rarities where slug = 'special'), 'Special', 1, 105),
  ('fortnite-gummy-seven', 'Gummy Seven', 'https://fortnite.gg/img/x/sprites/icons/T_Icon_BR_Creature_Sprite_Seven_Candy_ui_L.webp', (select id from public.categories where slug = 'fortnite'), (select id from public.rarities where slug = 'special'), 'Special', 1, 106),
  ('fortnite-galaxy-seven', 'Galaxy Seven', 'https://fortnite.gg/img/x/sprites/icons/T_Icon_BR_Creature_Sprite_Seven_Galaxy_ui_L.webp', (select id from public.categories where slug = 'fortnite'), (select id from public.rarities where slug = 'special'), 'Special', 1, 107),
  ('fortnite-holofoil-seven', 'Holofoil Seven', 'https://fortnite.gg/img/x/sprites/icons/T_Icon_BR_Creature_Sprite_Seven_Holofoil_ui_L.webp', (select id from public.categories where slug = 'fortnite'), (select id from public.rarities where slug = 'special'), 'Special', 1, 108),
  ('fortnite-gold-llama', 'Gold Llama', 'https://fortnite.gg/img/x/sprites/icons/T_Icon_BR_Creature_Sprite_Llama_Gold_ui_L.webp', (select id from public.categories where slug = 'fortnite'), (select id from public.rarities where slug = 'special'), 'Special', 1, 109),
  ('fortnite-gummy-llama', 'Gummy Llama', 'https://fortnite.gg/img/x/sprites/icons/T_Icon_BR_Creature_Sprite_Llama_Candy_ui_L.webp', (select id from public.categories where slug = 'fortnite'), (select id from public.rarities where slug = 'special'), 'Special', 1, 110),
  ('fortnite-galaxy-llama', 'Galaxy Llama', 'https://fortnite.gg/img/x/sprites/icons/T_Icon_BR_Creature_Sprite_Llama_Galaxy_ui_L.webp', (select id from public.categories where slug = 'fortnite'), (select id from public.rarities where slug = 'special'), 'Special', 1, 111),
  ('fortnite-gem-llama', 'Gem Llama', 'https://fortnite.gg/img/x/sprites/icons/T_Icon_BR_Creature_Sprite_Llama_Gem_ui_L.webp', (select id from public.categories where slug = 'fortnite'), (select id from public.rarities where slug = 'special'), 'Special', 1, 112),
  ('fortnite-gold-peely', 'Gold Peely', 'https://fortnite.gg/img/x/sprites/icons/T_Icon_BR_Creature_Sprite_Peely_Gold_ui_L.webp', (select id from public.categories where slug = 'fortnite'), (select id from public.rarities where slug = 'special'), 'Special', 1, 113),
  ('fortnite-gummy-peely', 'Gummy Peely', 'https://fortnite.gg/img/x/sprites/icons/T_Icon_BR_Creature_Sprite_Peely_Candy_ui_L.webp', (select id from public.categories where slug = 'fortnite'), (select id from public.rarities where slug = 'special'), 'Special', 1, 114),
  ('fortnite-galaxy-peely', 'Galaxy Peely', 'https://fortnite.gg/img/x/sprites/icons/T_Icon_BR_Creature_Sprite_Peely_Galaxy_ui_L.webp', (select id from public.categories where slug = 'fortnite'), (select id from public.rarities where slug = 'special'), 'Special', 1, 115),
  ('fortnite-holofoil-peely', 'Holofoil Peely', 'https://fortnite.gg/img/x/sprites/icons/T_Icon_BR_Creature_Sprite_Peely_Holofoil_ui_L.webp', (select id from public.categories where slug = 'fortnite'), (select id from public.rarities where slug = 'special'), 'Special', 1, 116),
  ('meme-1-de-paciencia', '1% de Paciencia', '/img/random/paciencia-1porcentaje.png', (select id from public.categories where slug = 'meme'), null, 'Meme', 1, 117),
  ('meme-this-is-fine', 'This Is Fine', '/img/random/this-is-fine.png', (select id from public.categories where slug = 'meme'), null, 'Meme', 1, 118),
  ('meme-no-entiendo', 'No entiendo', '/img/random/no-entiendo.png', (select id from public.categories where slug = 'meme'), null, 'Meme', 1, 119),
  ('meme-start', 'Start', '/img/random/start.png', (select id from public.categories where slug = 'meme'), null, 'Meme', 1, 120),
  ('dev-chispa-de-vida', 'Chispa de Vida', '/img/dev/chispa_de_vida.png', (select id from public.categories where slug = 'dev'), null, 'Dev', 1, 121),
  ('dev-exceso-de-ia', 'Exceso de IA', '/img/dev/exceso_de_ia.png', (select id from public.categories where slug = 'dev'), null, 'Dev', 1, 122),
  ('dev-github', 'GitHub', '/img/dev/github.png', (select id from public.categories where slug = 'dev'), null, 'Dev', 1, 123),
  ('dev-pure-coffee', 'Pure Coffee', '/img/dev/pure-coffee.png', (select id from public.categories where slug = 'dev'), null, 'Dev', 1, 124),
  ('dev-sin-internet', 'Sin Internet', '/img/dev/sin-internet.png', (select id from public.categories where slug = 'dev'), null, 'Dev', 1, 125),
  ('gato-boxeador', 'Gato Boxeador', '/img/gatos/gato-boxeador.png', (select id from public.categories where slug = 'gatos'), null, 'Gato', 1, 126),
  ('gato-blanco-triste', 'Gato Blanco Triste', '/img/gatos/gato-blanco-triste.png', (select id from public.categories where slug = 'gatos'), null, 'Gato', 1, 127),
  ('gatita-lazo-rosa', 'Gatita Lazo Rosa', '/img/gatos/gatita-lazo-rosa.png', (select id from public.categories where slug = 'gatos'), null, 'Gato', 1, 128),
  ('gatito-crema', 'Gatito Crema', '/img/gatos/gatito-crema.png', (select id from public.categories where slug = 'gatos'), null, 'Gato', 1, 129),
  ('gato-estirado', 'Gato Estirado', '/img/gatos/gato-estirado.png', (select id from public.categories where slug = 'gatos'), null, 'Gato', 1, 130),
  ('gato-lengua-afuera', 'Gato Lengua Afuera', '/img/gatos/gato-lengua-afuera.png', (select id from public.categories where slug = 'gatos'), null, 'Gato', 1, 131),
  ('gato-tengo-una-idea', 'Tengo una Idea', '/img/gatos/gato-tengo-una-idea.png', (select id from public.categories where slug = 'gatos'), null, 'Gato', 1, 132),
  ('gato-negro-nota', 'Gato Negro con Nota', '/img/gatos/gato-negro-nota.png', (select id from public.categories where slug = 'gatos'), null, 'Gato', 1, 133),
  ('gato-shhh', 'Gato Shhh', '/img/gatos/gato-shhh.png', (select id from public.categories where slug = 'gatos'), null, 'Gato', 1, 134),
  ('gato-estudiando', 'Gato Estudiando', '/img/gatos/gato-estudiando.png', (select id from public.categories where slug = 'gatos'), null, 'Gato', 1, 135),
  ('gato-negro-espia', 'Gato Negro Espia', '/img/gatos/gato-negro-espia.png', (select id from public.categories where slug = 'gatos'), null, 'Gato', 1, 136),
  ('gato-atigrado-espia', 'Gato Atigrado Espia', '/img/gatos/gato-atigrado-espia.png', (select id from public.categories where slug = 'gatos'), null, 'Gato', 1, 137),
  ('gato-mira-la-hora', 'Gato Mira la Hora', '/img/gatos/gato-mira-la-hora.png', (select id from public.categories where slug = 'gatos'), null, 'Gato', 1, 138),
  ('gato-rockero', 'Gato Rockero', '/img/gatos/gato-rockero.png', (select id from public.categories where slug = 'gatos'), null, 'Gato', 1, 139),
  ('gato-grunon', 'Gato Gruñon', '/img/gatos/gato-grunon.png', (select id from public.categories where slug = 'gatos'), null, 'Gato', 1, 140),
  ('gato-llorando', 'Gato Llorando', '/img/gatos/gato-llorando.png', (select id from public.categories where slug = 'gatos'), null, 'Gato', 1, 141),
  ('gato-billetera', 'Gato Billetera', '/img/gatos/gato-billetera.png', (select id from public.categories where slug = 'gatos'), null, 'Gato', 1, 142),
  ('frase-chill', 'Chill', '/img/frases/chill.png', (select id from public.categories where slug = 'frases'), null, 'Frase', 1, 143),
  ('frase-si-a-todo', 'Si a Todo', '/img/frases/si-a-todo.png', (select id from public.categories where slug = 'frases'), null, 'Frase', 1, 144),
  ('frase-si-se-puede', 'Si Se Puede', '/img/frases/si-se-puede.png', (select id from public.categories where slug = 'frases'), null, 'Frase', 1, 145),
  ('frase-focus', 'Focus', '/img/frases/focus.png', (select id from public.categories where slug = 'frases'), null, 'Frase', 1, 146),
  ('frase-focus-glitch', 'Focus Glitch', '/img/frases/focus-glitch.png', (select id from public.categories where slug = 'frases'), null, 'Frase', 1, 147),
  ('frase-blah-blah-blah', 'Blah Blah Blah', '/img/frases/blah-blah-blah.png', (select id from public.categories where slug = 'frases'), null, 'Frase', 1, 148),
  ('frase-modo-drama', 'Modo Drama', '/img/frases/modo-drama.png', (select id from public.categories where slug = 'frases'), null, 'Frase', 1, 149),
  ('frase-cero-interes', '0% Interes', '/img/frases/cero-interes.png', (select id from public.categories where slug = 'frases'), null, 'Frase', 1, 150),
  ('frase-sin-estres', 'Sin Estres', '/img/frases/sin-estres.png', (select id from public.categories where slug = 'frases'), null, 'Frase', 1, 151),
  ('frase-solo-se-que-no-se-nada', 'Solo Se Que No Se Nada', '/img/frases/solo-se-que-no-se-nada.png', (select id from public.categories where slug = 'frases'), null, 'Frase', 1, 152),
  ('frase-exceso-de-marketing', 'Exceso de Marketing', '/img/frases/exceso-de-marketing.png', (select id from public.categories where slug = 'frases'), null, 'Frase', 1, 153),
  ('frase-alto-contenido-de-fe', 'Alto Contenido de Fe', '/img/frases/alto-contenido-de-fe.png', (select id from public.categories where slug = 'frases'), null, 'Frase', 1, 154),
  ('dev-docker', 'Docker', '/img/dev/docker.png', (select id from public.categories where slug = 'dev'), null, 'Dev', 1, 155),
  ('dev-typescript', 'TypeScript', '/img/dev/typescript.png', (select id from public.categories where slug = 'dev'), null, 'Dev', 1, 156),
  ('dev-postman', 'Postman', '/img/dev/postman.png', (select id from public.categories where slug = 'dev'), null, 'Dev', 1, 157),
  ('dev-inteligencia-artificial', 'Inteligencia Artificial', '/img/dev/inteligencia-artificial.png', (select id from public.categories where slug = 'dev'), null, 'Dev', 1, 158),
  ('dev-panic-tabla-periodica', 'PaNIC', '/img/dev/panic-tabla-periodica.png', (select id from public.categories where slug = 'dev'), null, 'Dev', 1, 159),
  ('dev-sello-success', 'Success', '/img/dev/sello-success.png', (select id from public.categories where slug = 'dev'), null, 'Dev', 1, 160),
  ('dev-need-coffee', 'Need Coffee', '/img/dev/need-coffee.png', (select id from public.categories where slug = 'dev'), null, 'Dev', 1, 161),
  ('dev-espresso-patronum', 'Espresso Patronum', '/img/dev/espresso-patronum.png', (select id from public.categories where slug = 'dev'), null, 'Dev', 1, 162),
  ('dev-tecla-esc', 'Tecla ESC', '/img/dev/tecla-esc.png', (select id from public.categories where slug = 'dev'), null, 'Dev', 1, 163),
  ('dev-laptop-too-cute', 'Too Cute to Compute', '/img/dev/laptop-too-cute.png', (select id from public.categories where slug = 'dev'), null, 'Dev', 1, 164),
  ('dev-carpeta-pixel', 'Carpeta Pixel', '/img/dev/carpeta-pixel.png', (select id from public.categories where slug = 'dev'), null, 'Dev', 1, 165),
  ('dev-papelera-pixel', 'Papelera Pixel', '/img/dev/papelera-pixel.png', (select id from public.categories where slug = 'dev'), null, 'Dev', 1, 166),
  ('dev-nube-binaria', 'Nube Binaria', '/img/dev/nube-binaria.png', (select id from public.categories where slug = 'dev'), null, 'Dev', 1, 167),
  ('dev-loading-retro', 'Loading Retro', '/img/dev/loading-retro.png', (select id from public.categories where slug = 'dev'), null, 'Dev', 1, 168),
  ('dev-pinguinos-loading', 'Pinguinos Loading', '/img/dev/pinguinos-loading.png', (select id from public.categories where slug = 'dev'), null, 'Dev', 1, 169),
  ('meme-bateria-100', 'Bateria 100%', '/img/random/bateria-100.png', (select id from public.categories where slug = 'meme'), null, 'Meme', 1, 170),
  ('meme-bateria-60', 'Bateria 60%', '/img/random/bateria-60.png', (select id from public.categories where slug = 'meme'), null, 'Meme', 1, 171),
  ('meme-bateria-40', 'Bateria 40%', '/img/random/bateria-40.png', (select id from public.categories where slug = 'meme'), null, 'Meme', 1, 172),
  ('meme-bateria-20', 'Bateria 20%', '/img/random/bateria-20.png', (select id from public.categories where slug = 'meme'), null, 'Meme', 1, 173),
  ('meme-carita-feliz', 'Carita Feliz', '/img/random/carita-feliz.png', (select id from public.categories where slug = 'meme'), null, 'Meme', 1, 174),
  ('meme-seis-siete', '6-7', '/img/random/seis-siete.png', (select id from public.categories where slug = 'meme'), null, 'Meme', 1, 175),
  ('meme-tea-rex', 'Tea-Rex', '/img/random/tea-rex.png', (select id from public.categories where slug = 'meme'), null, 'Meme', 1, 176),
  ('meme-flork-musica', 'Flork Musica', '/img/random/flork-musica.png', (select id from public.categories where slug = 'meme'), null, 'Meme', 1, 177),
  ('meme-flork-acostado', 'Flork Acostado', '/img/random/flork-acostado.png', (select id from public.categories where slug = 'meme'), null, 'Meme', 1, 178),
  ('dev-angular', 'Angular', '/img/dev/angular.png', (select id from public.categories where slug = 'dev'), null, 'Dev', 1, 179),
  ('dev-aws', 'AWS', '/img/dev/aws.png', (select id from public.categories where slug = 'dev'), null, 'Dev', 1, 180),
  ('dev-aws-lambda', 'AWS Lambda', '/img/dev/aws-lambda.png', (select id from public.categories where slug = 'dev'), null, 'Dev', 1, 181),
  ('dev-aws-lambda-icono', 'AWS Lambda (icono)', '/img/dev/aws-lambda-icono.png', (select id from public.categories where slug = 'dev'), null, 'Dev', 1, 182),
  ('dev-azure', 'Azure', '/img/dev/azure.png', (select id from public.categories where slug = 'dev'), null, 'Dev', 1, 183),
  ('dev-azure-texto', 'Microsoft Azure', '/img/dev/azure-texto.png', (select id from public.categories where slug = 'dev'), null, 'Dev', 1, 184),
  ('dev-chatgpt', 'ChatGPT', '/img/dev/chatgpt.png', (select id from public.categories where slug = 'dev'), null, 'Dev', 1, 185),
  ('dev-openai', 'OpenAI', '/img/dev/openai.png', (select id from public.categories where slug = 'dev'), null, 'Dev', 1, 186),
  ('dev-copilot', 'Copilot', '/img/dev/copilot.png', (select id from public.categories where slug = 'dev'), null, 'Dev', 1, 187),
  ('dev-discord', 'Discord', '/img/dev/discord.png', (select id from public.categories where slug = 'dev'), null, 'Dev', 1, 188),
  ('dev-discord-texto', 'Discord (texto)', '/img/dev/discord-texto.png', (select id from public.categories where slug = 'dev'), null, 'Dev', 1, 189),
  ('dev-duolingo', 'Duolingo', '/img/dev/duolingo.png', (select id from public.categories where slug = 'dev'), null, 'Dev', 1, 190),
  ('dev-git', 'Git', '/img/dev/git.png', (select id from public.categories where slug = 'dev'), null, 'Dev', 1, 191),
  ('dev-git-bash', 'Git Bash', '/img/dev/git-bash.png', (select id from public.categories where slug = 'dev'), null, 'Dev', 1, 192),
  ('dev-github-texto', 'GitHub (texto)', '/img/dev/github-texto.png', (select id from public.categories where slug = 'dev'), null, 'Dev', 1, 193),
  ('dev-github-completo', 'GitHub', '/img/dev/github-completo.png', (select id from public.categories where slug = 'dev'), null, 'Dev', 1, 194),
  ('dev-github-icono', 'GitHub (icono)', '/img/dev/github-icono.png', (select id from public.categories where slug = 'dev'), null, 'Dev', 1, 195),
  ('dev-gitlab-texto', 'GitLab (texto)', '/img/dev/gitlab-texto.png', (select id from public.categories where slug = 'dev'), null, 'Dev', 1, 196),
  ('dev-gitlab', 'GitLab', '/img/dev/gitlab.png', (select id from public.categories where slug = 'dev'), null, 'Dev', 1, 197),
  ('dev-gitlab-wordmark', 'GitLab (wordmark)', '/img/dev/gitlab-wordmark.png', (select id from public.categories where slug = 'dev'), null, 'Dev', 1, 198),
  ('dev-java', 'Java', '/img/dev/java.png', (select id from public.categories where slug = 'dev'), null, 'Dev', 1, 199),
  ('dev-java-naranja', 'Java (naranja)', '/img/dev/java-naranja.png', (select id from public.categories where slug = 'dev'), null, 'Dev', 1, 200),
  ('dev-java-duke', 'Java Duke', '/img/dev/java-duke.png', (select id from public.categories where slug = 'dev'), null, 'Dev', 1, 201),
  ('dev-excel', 'Excel', '/img/dev/excel.png', (select id from public.categories where slug = 'dev'), null, 'Dev', 1, 202),
  ('dev-office', 'Office', '/img/dev/office.png', (select id from public.categories where slug = 'dev'), null, 'Dev', 1, 203),
  ('dev-powerpoint', 'PowerPoint', '/img/dev/powerpoint.png', (select id from public.categories where slug = 'dev'), null, 'Dev', 1, 204),
  ('dev-teams', 'Teams', '/img/dev/teams.png', (select id from public.categories where slug = 'dev'), null, 'Dev', 1, 205),
  ('dev-word', 'Word', '/img/dev/word.png', (select id from public.categories where slug = 'dev'), null, 'Dev', 1, 206),
  ('dev-minecraft', 'Minecraft', '/img/dev/minecraft.png', (select id from public.categories where slug = 'dev'), null, 'Dev', 1, 207),
  ('dev-nasa', 'NASA', '/img/dev/nasa.png', (select id from public.categories where slug = 'dev'), null, 'Dev', 1, 208),
  ('dev-nasa-negro', 'NASA (negro)', '/img/dev/nasa-negro.png', (select id from public.categories where slug = 'dev'), null, 'Dev', 1, 209),
  ('dev-nextjs', 'Next.js', '/img/dev/nextjs.png', (select id from public.categories where slug = 'dev'), null, 'Dev', 1, 210),
  ('dev-nextjs-cubo', 'Next (cubo)', '/img/dev/nextjs-cubo.png', (select id from public.categories where slug = 'dev'), null, 'Dev', 1, 211),
  ('dev-npm', 'npm', '/img/dev/npm.png', (select id from public.categories where slug = 'dev'), null, 'Dev', 1, 212),
  ('dev-npm-cubo', 'npm (cubo)', '/img/dev/npm-cubo.png', (select id from public.categories where slug = 'dev'), null, 'Dev', 1, 213),
  ('dev-npm-cuadrado', 'npm (cuadrado)', '/img/dev/npm-cuadrado.png', (select id from public.categories where slug = 'dev'), null, 'Dev', 1, 214),
  ('dev-nvidia', 'NVIDIA', '/img/dev/nvidia.png', (select id from public.categories where slug = 'dev'), null, 'Dev', 1, 215),
  ('dev-python', 'Python', '/img/dev/python.png', (select id from public.categories where slug = 'dev'), null, 'Dev', 1, 216),
  ('dev-python-texto', 'Python (texto)', '/img/dev/python-texto.png', (select id from public.categories where slug = 'dev'), null, 'Dev', 1, 217),
  ('dev-python-icono', 'Python (icono)', '/img/dev/python-icono.png', (select id from public.categories where slug = 'dev'), null, 'Dev', 1, 218),
  ('dev-pypi', 'PyPI', '/img/dev/pypi.png', (select id from public.categories where slug = 'dev'), null, 'Dev', 1, 219),
  ('dev-slack', 'Slack', '/img/dev/slack.png', (select id from public.categories where slug = 'dev'), null, 'Dev', 1, 220),
  ('dev-slack-icono', 'Slack (icono)', '/img/dev/slack-icono.png', (select id from public.categories where slug = 'dev'), null, 'Dev', 1, 221)
on conflict (slug) do update set
  name = excluded.name, image_url = excluded.image_url, category_id = excluded.category_id,
  rarity_id = excluded.rarity_id, rarity_label = excluded.rarity_label,
  price = excluded.price, sort_order = excluded.sort_order;

insert into public.tags (slug) values
  ('67'),
  ('aburrido'),
  ('ai'),
  ('amazon'),
  ('angular'),
  ('animo'),
  ('api'),
  ('archivos'),
  ('asomando'),
  ('atigrado'),
  ('audifonos'),
  ('aws'),
  ('azure'),
  ('backend'),
  ('baja'),
  ('bash'),
  ('basura'),
  ('bateria'),
  ('battle royale'),
  ('billetera'),
  ('binario'),
  ('blah'),
  ('blanco'),
  ('blep'),
  ('bloques'),
  ('box'),
  ('bug'),
  ('buho'),
  ('cafe'),
  ('calma'),
  ('cansado'),
  ('cargando'),
  ('carpeta'),
  ('cat'),
  ('chat'),
  ('chatgpt'),
  ('chill'),
  ('ciencia'),
  ('cloud'),
  ('code'),
  ('codigo'),
  ('coding'),
  ('coffee'),
  ('cohete'),
  ('compu'),
  ('comunidad'),
  ('concentracion'),
  ('consola'),
  ('contenedor'),
  ('control de versiones'),
  ('copilot'),
  ('crying cat'),
  ('deploy'),
  ('descanso'),
  ('dev'),
  ('developer'),
  ('devops'),
  ('dinero'),
  ('dino'),
  ('dinosaurio'),
  ('discord'),
  ('docker'),
  ('documento'),
  ('dormir'),
  ('drama'),
  ('duke'),
  ('duolingo'),
  ('energia'),
  ('enfoque'),
  ('enojado'),
  ('equipo'),
  ('esc'),
  ('escape'),
  ('espacio'),
  ('esperanza'),
  ('espia'),
  ('espiritus'),
  ('espresso'),
  ('estres'),
  ('estudio'),
  ('examen'),
  ('excel'),
  ('exito'),
  ('fe'),
  ('feliz'),
  ('filosofia'),
  ('flork'),
  ('fornite'),
  ('framework'),
  ('frase'),
  ('frases'),
  ('frontend'),
  ('full'),
  ('gatito'),
  ('gato'),
  ('gatos'),
  ('git'),
  ('github'),
  ('gitlab'),
  ('glitch'),
  ('gpt'),
  ('gpu'),
  ('grunon'),
  ('gráfica'),
  ('hablar'),
  ('hardware'),
  ('harry potter'),
  ('hojas'),
  ('hora'),
  ('ia'),
  ('idea'),
  ('idiomas'),
  ('interes'),
  ('java'),
  ('javascript'),
  ('juego'),
  ('jvm'),
  ('kitty'),
  ('lambda'),
  ('laptop'),
  ('lazo'),
  ('lengua'),
  ('linux'),
  ('llorando'),
  ('loading'),
  ('logo'),
  ('machine learning'),
  ('marketing'),
  ('mascota'),
  ('meme'),
  ('memes'),
  ('metal'),
  ('michi'),
  ('microsoft'),
  ('minecraft'),
  ('motivacion'),
  ('musica'),
  ('nasa'),
  ('negro'),
  ('next'),
  ('nextjs'),
  ('node'),
  ('nota'),
  ('npm'),
  ('nube'),
  ('nvidia'),
  ('octocat'),
  ('office'),
  ('ofimatica'),
  ('on'),
  ('openai'),
  ('panic'),
  ('papelera'),
  ('paquetes'),
  ('pelea'),
  ('pinguino'),
  ('pip'),
  ('pixel'),
  ('plata'),
  ('postman'),
  ('powerpoint'),
  ('ppt'),
  ('programacion'),
  ('publicidad'),
  ('pypi'),
  ('python'),
  ('quimica'),
  ('random'),
  ('react'),
  ('reloj'),
  ('repo'),
  ('rest'),
  ('retro'),
  ('reunion'),
  ('rock'),
  ('rosa'),
  ('script'),
  ('secreto'),
  ('seis siete'),
  ('serpiente'),
  ('serverless'),
  ('si'),
  ('silencio'),
  ('slack'),
  ('smiley'),
  ('socrates'),
  ('sonrisa'),
  ('sprites'),
  ('success'),
  ('tarde'),
  ('te'),
  ('tea'),
  ('teams'),
  ('tech'),
  ('teclado'),
  ('tendencia'),
  ('terminal'),
  ('texto'),
  ('tierno'),
  ('todo'),
  ('trabajo'),
  ('tranqui'),
  ('triste'),
  ('ts'),
  ('typescript'),
  ('vcs'),
  ('word'),
  ('yes'),
  ('zorro')
on conflict (slug) do nothing;

insert into public.sticker_tags (sticker_id, tag_id)
select s.id, t.id from (values
  ('fortnite-john-wick', 'fornite'),
  ('fortnite-john-wick', 'sprites'),
  ('fortnite-john-wick', 'battle royale'),
  ('fortnite-john-wick', 'espiritus'),
  ('fortnite-batman', 'fornite'),
  ('fortnite-batman', 'sprites'),
  ('fortnite-batman', 'battle royale'),
  ('fortnite-batman', 'espiritus'),
  ('fortnite-vini-jr', 'fornite'),
  ('fortnite-vini-jr', 'sprites'),
  ('fortnite-vini-jr', 'battle royale'),
  ('fortnite-vini-jr', 'espiritus'),
  ('fortnite-burnt-peanut', 'fornite'),
  ('fortnite-burnt-peanut', 'sprites'),
  ('fortnite-burnt-peanut', 'battle royale'),
  ('fortnite-burnt-peanut', 'espiritus'),
  ('fortnite-zero-point', 'fornite'),
  ('fortnite-zero-point', 'sprites'),
  ('fortnite-zero-point', 'battle royale'),
  ('fortnite-zero-point', 'espiritus'),
  ('fortnite-grim', 'fornite'),
  ('fortnite-grim', 'sprites'),
  ('fortnite-grim', 'battle royale'),
  ('fortnite-grim', 'espiritus'),
  ('fortnite-ironmouse', 'fornite'),
  ('fortnite-ironmouse', 'sprites'),
  ('fortnite-ironmouse', 'battle royale'),
  ('fortnite-ironmouse', 'espiritus'),
  ('fortnite-pollo', 'fornite'),
  ('fortnite-pollo', 'sprites'),
  ('fortnite-pollo', 'battle royale'),
  ('fortnite-pollo', 'espiritus'),
  ('fortnite-dream', 'fornite'),
  ('fortnite-dream', 'sprites'),
  ('fortnite-dream', 'battle royale'),
  ('fortnite-dream', 'espiritus'),
  ('fortnite-punk', 'fornite'),
  ('fortnite-punk', 'sprites'),
  ('fortnite-punk', 'battle royale'),
  ('fortnite-punk', 'espiritus'),
  ('fortnite-boss', 'fornite'),
  ('fortnite-boss', 'sprites'),
  ('fortnite-boss', 'battle royale'),
  ('fortnite-boss', 'espiritus'),
  ('fortnite-seven', 'fornite'),
  ('fortnite-seven', 'sprites'),
  ('fortnite-seven', 'battle royale'),
  ('fortnite-seven', 'espiritus'),
  ('fortnite-llama', 'fornite'),
  ('fortnite-llama', 'sprites'),
  ('fortnite-llama', 'battle royale'),
  ('fortnite-llama', 'espiritus'),
  ('fortnite-peely', 'fornite'),
  ('fortnite-peely', 'sprites'),
  ('fortnite-peely', 'battle royale'),
  ('fortnite-peely', 'espiritus'),
  ('fortnite-duck', 'fornite'),
  ('fortnite-duck', 'sprites'),
  ('fortnite-duck', 'battle royale'),
  ('fortnite-duck', 'espiritus'),
  ('fortnite-ghost', 'fornite'),
  ('fortnite-ghost', 'sprites'),
  ('fortnite-ghost', 'battle royale'),
  ('fortnite-ghost', 'espiritus'),
  ('fortnite-demon', 'fornite'),
  ('fortnite-demon', 'sprites'),
  ('fortnite-demon', 'battle royale'),
  ('fortnite-demon', 'espiritus'),
  ('fortnite-king', 'fornite'),
  ('fortnite-king', 'sprites'),
  ('fortnite-king', 'battle royale'),
  ('fortnite-king', 'espiritus'),
  ('fortnite-striker', 'fornite'),
  ('fortnite-striker', 'sprites'),
  ('fortnite-striker', 'battle royale'),
  ('fortnite-striker', 'espiritus'),
  ('fortnite-aura', 'fornite'),
  ('fortnite-aura', 'sprites'),
  ('fortnite-aura', 'battle royale'),
  ('fortnite-aura', 'espiritus'),
  ('fortnite-water', 'fornite'),
  ('fortnite-water', 'sprites'),
  ('fortnite-water', 'battle royale'),
  ('fortnite-water', 'espiritus'),
  ('fortnite-earth', 'fornite'),
  ('fortnite-earth', 'sprites'),
  ('fortnite-earth', 'battle royale'),
  ('fortnite-earth', 'espiritus'),
  ('fortnite-fire', 'fornite'),
  ('fortnite-fire', 'sprites'),
  ('fortnite-fire', 'battle royale'),
  ('fortnite-fire', 'espiritus'),
  ('fortnite-fishy', 'fornite'),
  ('fortnite-fishy', 'sprites'),
  ('fortnite-fishy', 'battle royale'),
  ('fortnite-fishy', 'espiritus'),
  ('fortnite-air', 'fornite'),
  ('fortnite-air', 'sprites'),
  ('fortnite-air', 'battle royale'),
  ('fortnite-air', 'espiritus'),
  ('fortnite-cube-batman', 'fornite'),
  ('fortnite-cube-batman', 'sprites'),
  ('fortnite-cube-batman', 'battle royale'),
  ('fortnite-cube-batman', 'espiritus'),
  ('fortnite-gold-batman', 'fornite'),
  ('fortnite-gold-batman', 'sprites'),
  ('fortnite-gold-batman', 'battle royale'),
  ('fortnite-gold-batman', 'espiritus'),
  ('fortnite-gummy-batman', 'fornite'),
  ('fortnite-gummy-batman', 'sprites'),
  ('fortnite-gummy-batman', 'battle royale'),
  ('fortnite-gummy-batman', 'espiritus'),
  ('fortnite-galaxy-batman', 'fornite'),
  ('fortnite-galaxy-batman', 'sprites'),
  ('fortnite-galaxy-batman', 'battle royale'),
  ('fortnite-galaxy-batman', 'espiritus'),
  ('fortnite-holofoil-batman', 'fornite'),
  ('fortnite-holofoil-batman', 'sprites'),
  ('fortnite-holofoil-batman', 'battle royale'),
  ('fortnite-holofoil-batman', 'espiritus'),
  ('fortnite-gold-water', 'fornite'),
  ('fortnite-gold-water', 'sprites'),
  ('fortnite-gold-water', 'battle royale'),
  ('fortnite-gold-water', 'espiritus'),
  ('fortnite-quack-water', 'fornite'),
  ('fortnite-quack-water', 'sprites'),
  ('fortnite-quack-water', 'battle royale'),
  ('fortnite-quack-water', 'espiritus'),
  ('fortnite-gummy-water', 'fornite'),
  ('fortnite-gummy-water', 'sprites'),
  ('fortnite-gummy-water', 'battle royale'),
  ('fortnite-gummy-water', 'espiritus'),
  ('fortnite-galaxy-water', 'fornite'),
  ('fortnite-galaxy-water', 'sprites'),
  ('fortnite-galaxy-water', 'battle royale'),
  ('fortnite-galaxy-water', 'espiritus'),
  ('fortnite-gem-water', 'fornite'),
  ('fortnite-gem-water', 'sprites'),
  ('fortnite-gem-water', 'battle royale'),
  ('fortnite-gem-water', 'espiritus'),
  ('fortnite-holofoil-water', 'fornite'),
  ('fortnite-holofoil-water', 'sprites'),
  ('fortnite-holofoil-water', 'battle royale'),
  ('fortnite-holofoil-water', 'espiritus'),
  ('fortnite-cube-earth', 'fornite'),
  ('fortnite-cube-earth', 'sprites'),
  ('fortnite-cube-earth', 'battle royale'),
  ('fortnite-cube-earth', 'espiritus'),
  ('fortnite-gold-earth', 'fornite'),
  ('fortnite-gold-earth', 'sprites'),
  ('fortnite-gold-earth', 'battle royale'),
  ('fortnite-gold-earth', 'espiritus'),
  ('fortnite-quack-earth', 'fornite'),
  ('fortnite-quack-earth', 'sprites'),
  ('fortnite-quack-earth', 'battle royale'),
  ('fortnite-quack-earth', 'espiritus'),
  ('fortnite-gummy-earth', 'fornite'),
  ('fortnite-gummy-earth', 'sprites'),
  ('fortnite-gummy-earth', 'battle royale'),
  ('fortnite-gummy-earth', 'espiritus'),
  ('fortnite-galaxy-earth', 'fornite'),
  ('fortnite-galaxy-earth', 'sprites'),
  ('fortnite-galaxy-earth', 'battle royale'),
  ('fortnite-galaxy-earth', 'espiritus'),
  ('fortnite-gem-earth', 'fornite'),
  ('fortnite-gem-earth', 'sprites'),
  ('fortnite-gem-earth', 'battle royale'),
  ('fortnite-gem-earth', 'espiritus'),
  ('fortnite-cube-fire', 'fornite'),
  ('fortnite-cube-fire', 'sprites'),
  ('fortnite-cube-fire', 'battle royale'),
  ('fortnite-cube-fire', 'espiritus'),
  ('fortnite-gold-fire', 'fornite'),
  ('fortnite-gold-fire', 'sprites'),
  ('fortnite-gold-fire', 'battle royale'),
  ('fortnite-gold-fire', 'espiritus'),
  ('fortnite-quack-fire', 'fornite'),
  ('fortnite-quack-fire', 'sprites'),
  ('fortnite-quack-fire', 'battle royale'),
  ('fortnite-quack-fire', 'espiritus'),
  ('fortnite-gummy-fire', 'fornite'),
  ('fortnite-gummy-fire', 'sprites'),
  ('fortnite-gummy-fire', 'battle royale'),
  ('fortnite-gummy-fire', 'espiritus'),
  ('fortnite-galaxy-fire', 'fornite'),
  ('fortnite-galaxy-fire', 'sprites'),
  ('fortnite-galaxy-fire', 'battle royale'),
  ('fortnite-galaxy-fire', 'espiritus'),
  ('fortnite-holofoil-fire', 'fornite'),
  ('fortnite-holofoil-fire', 'sprites'),
  ('fortnite-holofoil-fire', 'battle royale'),
  ('fortnite-holofoil-fire', 'espiritus'),
  ('fortnite-gold-duck', 'fornite'),
  ('fortnite-gold-duck', 'sprites'),
  ('fortnite-gold-duck', 'battle royale'),
  ('fortnite-gold-duck', 'espiritus'),
  ('fortnite-gummy-duck', 'fornite'),
  ('fortnite-gummy-duck', 'sprites'),
  ('fortnite-gummy-duck', 'battle royale'),
  ('fortnite-gummy-duck', 'espiritus'),
  ('fortnite-galaxy-duck', 'fornite'),
  ('fortnite-galaxy-duck', 'sprites'),
  ('fortnite-galaxy-duck', 'battle royale'),
  ('fortnite-galaxy-duck', 'espiritus'),
  ('fortnite-gem-duck', 'fornite'),
  ('fortnite-gem-duck', 'sprites'),
  ('fortnite-gem-duck', 'battle royale'),
  ('fortnite-gem-duck', 'espiritus'),
  ('fortnite-gold-ghost', 'fornite'),
  ('fortnite-gold-ghost', 'sprites'),
  ('fortnite-gold-ghost', 'battle royale'),
  ('fortnite-gold-ghost', 'espiritus'),
  ('fortnite-gummy-ghost', 'fornite'),
  ('fortnite-gummy-ghost', 'sprites'),
  ('fortnite-gummy-ghost', 'battle royale'),
  ('fortnite-gummy-ghost', 'espiritus'),
  ('fortnite-galaxy-ghost', 'fornite'),
  ('fortnite-galaxy-ghost', 'sprites'),
  ('fortnite-galaxy-ghost', 'battle royale'),
  ('fortnite-galaxy-ghost', 'espiritus'),
  ('fortnite-holofoil-ghost', 'fornite'),
  ('fortnite-holofoil-ghost', 'sprites'),
  ('fortnite-holofoil-ghost', 'battle royale'),
  ('fortnite-holofoil-ghost', 'espiritus'),
  ('fortnite-cube-dream', 'fornite'),
  ('fortnite-cube-dream', 'sprites'),
  ('fortnite-cube-dream', 'battle royale'),
  ('fortnite-cube-dream', 'espiritus'),
  ('fortnite-gold-dream', 'fornite'),
  ('fortnite-gold-dream', 'sprites'),
  ('fortnite-gold-dream', 'battle royale'),
  ('fortnite-gold-dream', 'espiritus'),
  ('fortnite-gummy-dream', 'fornite'),
  ('fortnite-gummy-dream', 'sprites'),
  ('fortnite-gummy-dream', 'battle royale'),
  ('fortnite-gummy-dream', 'espiritus'),
  ('fortnite-galaxy-dream', 'fornite'),
  ('fortnite-galaxy-dream', 'sprites'),
  ('fortnite-galaxy-dream', 'battle royale'),
  ('fortnite-galaxy-dream', 'espiritus'),
  ('fortnite-gold-demon', 'fornite'),
  ('fortnite-gold-demon', 'sprites'),
  ('fortnite-gold-demon', 'battle royale'),
  ('fortnite-gold-demon', 'espiritus'),
  ('fortnite-gummy-demon', 'fornite'),
  ('fortnite-gummy-demon', 'sprites'),
  ('fortnite-gummy-demon', 'battle royale'),
  ('fortnite-gummy-demon', 'espiritus'),
  ('fortnite-galaxy-demon', 'fornite'),
  ('fortnite-galaxy-demon', 'sprites'),
  ('fortnite-galaxy-demon', 'battle royale'),
  ('fortnite-galaxy-demon', 'espiritus'),
  ('fortnite-gem-demon', 'fornite'),
  ('fortnite-gem-demon', 'sprites'),
  ('fortnite-gem-demon', 'battle royale'),
  ('fortnite-gem-demon', 'espiritus'),
  ('fortnite-cube-punk', 'fornite'),
  ('fortnite-cube-punk', 'sprites'),
  ('fortnite-cube-punk', 'battle royale'),
  ('fortnite-cube-punk', 'espiritus'),
  ('fortnite-gold-punk', 'fornite'),
  ('fortnite-gold-punk', 'sprites'),
  ('fortnite-gold-punk', 'battle royale'),
  ('fortnite-gold-punk', 'espiritus'),
  ('fortnite-gummy-punk', 'fornite'),
  ('fortnite-gummy-punk', 'sprites'),
  ('fortnite-gummy-punk', 'battle royale'),
  ('fortnite-gummy-punk', 'espiritus'),
  ('fortnite-galaxy-punk', 'fornite'),
  ('fortnite-galaxy-punk', 'sprites'),
  ('fortnite-galaxy-punk', 'battle royale'),
  ('fortnite-galaxy-punk', 'espiritus'),
  ('fortnite-gold-king', 'fornite'),
  ('fortnite-gold-king', 'sprites'),
  ('fortnite-gold-king', 'battle royale'),
  ('fortnite-gold-king', 'espiritus'),
  ('fortnite-gummy-king', 'fornite'),
  ('fortnite-gummy-king', 'sprites'),
  ('fortnite-gummy-king', 'battle royale'),
  ('fortnite-gummy-king', 'espiritus'),
  ('fortnite-galaxy-king', 'fornite'),
  ('fortnite-galaxy-king', 'sprites'),
  ('fortnite-galaxy-king', 'battle royale'),
  ('fortnite-galaxy-king', 'espiritus'),
  ('fortnite-holofoil-king', 'fornite'),
  ('fortnite-holofoil-king', 'sprites'),
  ('fortnite-holofoil-king', 'battle royale'),
  ('fortnite-holofoil-king', 'espiritus'),
  ('fortnite-cube-zero-point', 'fornite'),
  ('fortnite-cube-zero-point', 'sprites'),
  ('fortnite-cube-zero-point', 'battle royale'),
  ('fortnite-cube-zero-point', 'espiritus'),
  ('fortnite-gold-zero-point', 'fornite'),
  ('fortnite-gold-zero-point', 'sprites'),
  ('fortnite-gold-zero-point', 'battle royale'),
  ('fortnite-gold-zero-point', 'espiritus'),
  ('fortnite-quack-zero-point', 'fornite'),
  ('fortnite-quack-zero-point', 'sprites'),
  ('fortnite-quack-zero-point', 'battle royale'),
  ('fortnite-quack-zero-point', 'espiritus'),
  ('fortnite-gummy-zero-point', 'fornite'),
  ('fortnite-gummy-zero-point', 'sprites'),
  ('fortnite-gummy-zero-point', 'battle royale'),
  ('fortnite-gummy-zero-point', 'espiritus'),
  ('fortnite-galaxy-zero-point', 'fornite'),
  ('fortnite-galaxy-zero-point', 'sprites'),
  ('fortnite-galaxy-zero-point', 'battle royale'),
  ('fortnite-galaxy-zero-point', 'espiritus'),
  ('fortnite-gem-zero-point', 'fornite'),
  ('fortnite-gem-zero-point', 'sprites'),
  ('fortnite-gem-zero-point', 'battle royale'),
  ('fortnite-gem-zero-point', 'espiritus'),
  ('fortnite-holofoil-zero-point', 'fornite'),
  ('fortnite-holofoil-zero-point', 'sprites'),
  ('fortnite-holofoil-zero-point', 'battle royale'),
  ('fortnite-holofoil-zero-point', 'espiritus'),
  ('fortnite-cube-fishy', 'fornite'),
  ('fortnite-cube-fishy', 'sprites'),
  ('fortnite-cube-fishy', 'battle royale'),
  ('fortnite-cube-fishy', 'espiritus'),
  ('fortnite-gold-fishy', 'fornite'),
  ('fortnite-gold-fishy', 'sprites'),
  ('fortnite-gold-fishy', 'battle royale'),
  ('fortnite-gold-fishy', 'espiritus'),
  ('fortnite-gummy-fishy', 'fornite'),
  ('fortnite-gummy-fishy', 'sprites'),
  ('fortnite-gummy-fishy', 'battle royale'),
  ('fortnite-gummy-fishy', 'espiritus'),
  ('fortnite-galaxy-fishy', 'fornite'),
  ('fortnite-galaxy-fishy', 'sprites'),
  ('fortnite-galaxy-fishy', 'battle royale'),
  ('fortnite-galaxy-fishy', 'espiritus'),
  ('fortnite-gold-striker', 'fornite'),
  ('fortnite-gold-striker', 'sprites'),
  ('fortnite-gold-striker', 'battle royale'),
  ('fortnite-gold-striker', 'espiritus'),
  ('fortnite-gummy-striker', 'fornite'),
  ('fortnite-gummy-striker', 'sprites'),
  ('fortnite-gummy-striker', 'battle royale'),
  ('fortnite-gummy-striker', 'espiritus'),
  ('fortnite-galaxy-striker', 'fornite'),
  ('fortnite-galaxy-striker', 'sprites'),
  ('fortnite-galaxy-striker', 'battle royale'),
  ('fortnite-galaxy-striker', 'espiritus'),
  ('fortnite-holofoil-striker', 'fornite'),
  ('fortnite-holofoil-striker', 'sprites'),
  ('fortnite-holofoil-striker', 'battle royale'),
  ('fortnite-holofoil-striker', 'espiritus'),
  ('fortnite-gold-aura', 'fornite'),
  ('fortnite-gold-aura', 'sprites'),
  ('fortnite-gold-aura', 'battle royale'),
  ('fortnite-gold-aura', 'espiritus'),
  ('fortnite-gummy-aura', 'fornite'),
  ('fortnite-gummy-aura', 'sprites'),
  ('fortnite-gummy-aura', 'battle royale'),
  ('fortnite-gummy-aura', 'espiritus'),
  ('fortnite-galaxy-aura', 'fornite'),
  ('fortnite-galaxy-aura', 'sprites'),
  ('fortnite-galaxy-aura', 'battle royale'),
  ('fortnite-galaxy-aura', 'espiritus'),
  ('fortnite-gem-aura', 'fornite'),
  ('fortnite-gem-aura', 'sprites'),
  ('fortnite-gem-aura', 'battle royale'),
  ('fortnite-gem-aura', 'espiritus'),
  ('fortnite-cube-boss', 'fornite'),
  ('fortnite-cube-boss', 'sprites'),
  ('fortnite-cube-boss', 'battle royale'),
  ('fortnite-cube-boss', 'espiritus'),
  ('fortnite-gold-boss', 'fornite'),
  ('fortnite-gold-boss', 'sprites'),
  ('fortnite-gold-boss', 'battle royale'),
  ('fortnite-gold-boss', 'espiritus'),
  ('fortnite-gummy-boss', 'fornite'),
  ('fortnite-gummy-boss', 'sprites'),
  ('fortnite-gummy-boss', 'battle royale'),
  ('fortnite-gummy-boss', 'espiritus'),
  ('fortnite-galaxy-boss', 'fornite'),
  ('fortnite-galaxy-boss', 'sprites'),
  ('fortnite-galaxy-boss', 'battle royale'),
  ('fortnite-galaxy-boss', 'espiritus'),
  ('fortnite-cube-grim', 'fornite'),
  ('fortnite-cube-grim', 'sprites'),
  ('fortnite-cube-grim', 'battle royale'),
  ('fortnite-cube-grim', 'espiritus'),
  ('fortnite-gold-grim', 'fornite'),
  ('fortnite-gold-grim', 'sprites'),
  ('fortnite-gold-grim', 'battle royale'),
  ('fortnite-gold-grim', 'espiritus'),
  ('fortnite-gummy-grim', 'fornite'),
  ('fortnite-gummy-grim', 'sprites'),
  ('fortnite-gummy-grim', 'battle royale'),
  ('fortnite-gummy-grim', 'espiritus'),
  ('fortnite-galaxy-grim', 'fornite'),
  ('fortnite-galaxy-grim', 'sprites'),
  ('fortnite-galaxy-grim', 'battle royale'),
  ('fortnite-galaxy-grim', 'espiritus'),
  ('fortnite-gem-grim', 'fornite'),
  ('fortnite-gem-grim', 'sprites'),
  ('fortnite-gem-grim', 'battle royale'),
  ('fortnite-gem-grim', 'espiritus'),
  ('fortnite-holofoil-grim', 'fornite'),
  ('fortnite-holofoil-grim', 'sprites'),
  ('fortnite-holofoil-grim', 'battle royale'),
  ('fortnite-holofoil-grim', 'espiritus'),
  ('fortnite-gold-air', 'fornite'),
  ('fortnite-gold-air', 'sprites'),
  ('fortnite-gold-air', 'battle royale'),
  ('fortnite-gold-air', 'espiritus'),
  ('fortnite-gummy-air', 'fornite'),
  ('fortnite-gummy-air', 'sprites'),
  ('fortnite-gummy-air', 'battle royale'),
  ('fortnite-gummy-air', 'espiritus'),
  ('fortnite-galaxy-air', 'fornite'),
  ('fortnite-galaxy-air', 'sprites'),
  ('fortnite-galaxy-air', 'battle royale'),
  ('fortnite-galaxy-air', 'espiritus'),
  ('fortnite-holofoil-air', 'fornite'),
  ('fortnite-holofoil-air', 'sprites'),
  ('fortnite-holofoil-air', 'battle royale'),
  ('fortnite-holofoil-air', 'espiritus'),
  ('fortnite-gold-seven', 'fornite'),
  ('fortnite-gold-seven', 'sprites'),
  ('fortnite-gold-seven', 'battle royale'),
  ('fortnite-gold-seven', 'espiritus'),
  ('fortnite-gummy-seven', 'fornite'),
  ('fortnite-gummy-seven', 'sprites'),
  ('fortnite-gummy-seven', 'battle royale'),
  ('fortnite-gummy-seven', 'espiritus'),
  ('fortnite-galaxy-seven', 'fornite'),
  ('fortnite-galaxy-seven', 'sprites'),
  ('fortnite-galaxy-seven', 'battle royale'),
  ('fortnite-galaxy-seven', 'espiritus'),
  ('fortnite-holofoil-seven', 'fornite'),
  ('fortnite-holofoil-seven', 'sprites'),
  ('fortnite-holofoil-seven', 'battle royale'),
  ('fortnite-holofoil-seven', 'espiritus'),
  ('fortnite-gold-llama', 'fornite'),
  ('fortnite-gold-llama', 'sprites'),
  ('fortnite-gold-llama', 'battle royale'),
  ('fortnite-gold-llama', 'espiritus'),
  ('fortnite-gummy-llama', 'fornite'),
  ('fortnite-gummy-llama', 'sprites'),
  ('fortnite-gummy-llama', 'battle royale'),
  ('fortnite-gummy-llama', 'espiritus'),
  ('fortnite-galaxy-llama', 'fornite'),
  ('fortnite-galaxy-llama', 'sprites'),
  ('fortnite-galaxy-llama', 'battle royale'),
  ('fortnite-galaxy-llama', 'espiritus'),
  ('fortnite-gem-llama', 'fornite'),
  ('fortnite-gem-llama', 'sprites'),
  ('fortnite-gem-llama', 'battle royale'),
  ('fortnite-gem-llama', 'espiritus'),
  ('fortnite-gold-peely', 'fornite'),
  ('fortnite-gold-peely', 'sprites'),
  ('fortnite-gold-peely', 'battle royale'),
  ('fortnite-gold-peely', 'espiritus'),
  ('fortnite-gummy-peely', 'fornite'),
  ('fortnite-gummy-peely', 'sprites'),
  ('fortnite-gummy-peely', 'battle royale'),
  ('fortnite-gummy-peely', 'espiritus'),
  ('fortnite-galaxy-peely', 'fornite'),
  ('fortnite-galaxy-peely', 'sprites'),
  ('fortnite-galaxy-peely', 'battle royale'),
  ('fortnite-galaxy-peely', 'espiritus'),
  ('fortnite-holofoil-peely', 'fornite'),
  ('fortnite-holofoil-peely', 'sprites'),
  ('fortnite-holofoil-peely', 'battle royale'),
  ('fortnite-holofoil-peely', 'espiritus'),
  ('meme-1-de-paciencia', 'meme'),
  ('meme-1-de-paciencia', 'memes'),
  ('meme-1-de-paciencia', 'random'),
  ('meme-this-is-fine', 'meme'),
  ('meme-this-is-fine', 'memes'),
  ('meme-this-is-fine', 'random'),
  ('meme-no-entiendo', 'meme'),
  ('meme-no-entiendo', 'memes'),
  ('meme-no-entiendo', 'random'),
  ('meme-start', 'meme'),
  ('meme-start', 'memes'),
  ('meme-start', 'random'),
  ('dev-chispa-de-vida', 'dev'),
  ('dev-chispa-de-vida', 'code'),
  ('dev-chispa-de-vida', 'programacion'),
  ('dev-chispa-de-vida', 'developer'),
  ('dev-chispa-de-vida', 'coding'),
  ('dev-chispa-de-vida', 'tech'),
  ('dev-chispa-de-vida', 'codigo'),
  ('dev-exceso-de-ia', 'dev'),
  ('dev-exceso-de-ia', 'code'),
  ('dev-exceso-de-ia', 'programacion'),
  ('dev-exceso-de-ia', 'developer'),
  ('dev-exceso-de-ia', 'coding'),
  ('dev-exceso-de-ia', 'tech'),
  ('dev-exceso-de-ia', 'codigo'),
  ('dev-github', 'dev'),
  ('dev-github', 'code'),
  ('dev-github', 'programacion'),
  ('dev-github', 'developer'),
  ('dev-github', 'coding'),
  ('dev-github', 'tech'),
  ('dev-github', 'codigo'),
  ('dev-pure-coffee', 'dev'),
  ('dev-pure-coffee', 'code'),
  ('dev-pure-coffee', 'programacion'),
  ('dev-pure-coffee', 'developer'),
  ('dev-pure-coffee', 'coding'),
  ('dev-pure-coffee', 'tech'),
  ('dev-pure-coffee', 'codigo'),
  ('dev-sin-internet', 'dev'),
  ('dev-sin-internet', 'code'),
  ('dev-sin-internet', 'programacion'),
  ('dev-sin-internet', 'developer'),
  ('dev-sin-internet', 'coding'),
  ('dev-sin-internet', 'tech'),
  ('dev-sin-internet', 'codigo'),
  ('gato-boxeador', 'gato'),
  ('gato-boxeador', 'gatos'),
  ('gato-boxeador', 'cat'),
  ('gato-boxeador', 'meme'),
  ('gato-boxeador', 'michi'),
  ('gato-boxeador', 'box'),
  ('gato-boxeador', 'pelea'),
  ('gato-blanco-triste', 'gato'),
  ('gato-blanco-triste', 'gatos'),
  ('gato-blanco-triste', 'cat'),
  ('gato-blanco-triste', 'meme'),
  ('gato-blanco-triste', 'michi'),
  ('gato-blanco-triste', 'triste'),
  ('gato-blanco-triste', 'blanco'),
  ('gatita-lazo-rosa', 'gato'),
  ('gatita-lazo-rosa', 'gatos'),
  ('gatita-lazo-rosa', 'cat'),
  ('gatita-lazo-rosa', 'meme'),
  ('gatita-lazo-rosa', 'michi'),
  ('gatita-lazo-rosa', 'kitty'),
  ('gatita-lazo-rosa', 'rosa'),
  ('gatita-lazo-rosa', 'lazo'),
  ('gatito-crema', 'gato'),
  ('gatito-crema', 'gatos'),
  ('gatito-crema', 'cat'),
  ('gatito-crema', 'meme'),
  ('gatito-crema', 'michi'),
  ('gatito-crema', 'gatito'),
  ('gatito-crema', 'tierno'),
  ('gato-estirado', 'gato'),
  ('gato-estirado', 'gatos'),
  ('gato-estirado', 'cat'),
  ('gato-estirado', 'meme'),
  ('gato-estirado', 'michi'),
  ('gato-estirado', 'cansado'),
  ('gato-estirado', 'dormir'),
  ('gato-lengua-afuera', 'gato'),
  ('gato-lengua-afuera', 'gatos'),
  ('gato-lengua-afuera', 'cat'),
  ('gato-lengua-afuera', 'meme'),
  ('gato-lengua-afuera', 'michi'),
  ('gato-lengua-afuera', 'lengua'),
  ('gato-lengua-afuera', 'blep'),
  ('gato-tengo-una-idea', 'gato'),
  ('gato-tengo-una-idea', 'gatos'),
  ('gato-tengo-una-idea', 'cat'),
  ('gato-tengo-una-idea', 'meme'),
  ('gato-tengo-una-idea', 'michi'),
  ('gato-tengo-una-idea', 'idea'),
  ('gato-negro-nota', 'gato'),
  ('gato-negro-nota', 'gatos'),
  ('gato-negro-nota', 'cat'),
  ('gato-negro-nota', 'meme'),
  ('gato-negro-nota', 'michi'),
  ('gato-negro-nota', 'negro'),
  ('gato-negro-nota', 'nota'),
  ('gato-shhh', 'gato'),
  ('gato-shhh', 'gatos'),
  ('gato-shhh', 'cat'),
  ('gato-shhh', 'meme'),
  ('gato-shhh', 'michi'),
  ('gato-shhh', 'silencio'),
  ('gato-shhh', 'secreto'),
  ('gato-estudiando', 'gato'),
  ('gato-estudiando', 'gatos'),
  ('gato-estudiando', 'cat'),
  ('gato-estudiando', 'meme'),
  ('gato-estudiando', 'michi'),
  ('gato-estudiando', 'estudio'),
  ('gato-estudiando', 'examen'),
  ('gato-negro-espia', 'gato'),
  ('gato-negro-espia', 'gatos'),
  ('gato-negro-espia', 'cat'),
  ('gato-negro-espia', 'meme'),
  ('gato-negro-espia', 'michi'),
  ('gato-negro-espia', 'negro'),
  ('gato-negro-espia', 'espia'),
  ('gato-negro-espia', 'asomando'),
  ('gato-atigrado-espia', 'gato'),
  ('gato-atigrado-espia', 'gatos'),
  ('gato-atigrado-espia', 'cat'),
  ('gato-atigrado-espia', 'meme'),
  ('gato-atigrado-espia', 'michi'),
  ('gato-atigrado-espia', 'atigrado'),
  ('gato-atigrado-espia', 'espia'),
  ('gato-mira-la-hora', 'gato'),
  ('gato-mira-la-hora', 'gatos'),
  ('gato-mira-la-hora', 'cat'),
  ('gato-mira-la-hora', 'meme'),
  ('gato-mira-la-hora', 'michi'),
  ('gato-mira-la-hora', 'reloj'),
  ('gato-mira-la-hora', 'hora'),
  ('gato-mira-la-hora', 'tarde'),
  ('gato-rockero', 'gato'),
  ('gato-rockero', 'gatos'),
  ('gato-rockero', 'cat'),
  ('gato-rockero', 'meme'),
  ('gato-rockero', 'michi'),
  ('gato-rockero', 'rock'),
  ('gato-rockero', 'metal'),
  ('gato-grunon', 'gato'),
  ('gato-grunon', 'gatos'),
  ('gato-grunon', 'cat'),
  ('gato-grunon', 'meme'),
  ('gato-grunon', 'michi'),
  ('gato-grunon', 'enojado'),
  ('gato-grunon', 'grunon'),
  ('gato-llorando', 'gato'),
  ('gato-llorando', 'gatos'),
  ('gato-llorando', 'cat'),
  ('gato-llorando', 'meme'),
  ('gato-llorando', 'michi'),
  ('gato-llorando', 'llorando'),
  ('gato-llorando', 'crying cat'),
  ('gato-billetera', 'gato'),
  ('gato-billetera', 'gatos'),
  ('gato-billetera', 'cat'),
  ('gato-billetera', 'meme'),
  ('gato-billetera', 'michi'),
  ('gato-billetera', 'dinero'),
  ('gato-billetera', 'plata'),
  ('gato-billetera', 'billetera'),
  ('frase-chill', 'frase'),
  ('frase-chill', 'frases'),
  ('frase-chill', 'texto'),
  ('frase-chill', 'motivacion'),
  ('frase-chill', 'chill'),
  ('frase-chill', 'calma'),
  ('frase-chill', 'tranqui'),
  ('frase-si-a-todo', 'frase'),
  ('frase-si-a-todo', 'frases'),
  ('frase-si-a-todo', 'texto'),
  ('frase-si-a-todo', 'motivacion'),
  ('frase-si-a-todo', 'si'),
  ('frase-si-a-todo', 'todo'),
  ('frase-si-a-todo', 'yes'),
  ('frase-si-se-puede', 'frase'),
  ('frase-si-se-puede', 'frases'),
  ('frase-si-se-puede', 'texto'),
  ('frase-si-se-puede', 'motivacion'),
  ('frase-si-se-puede', 'animo'),
  ('frase-focus', 'frase'),
  ('frase-focus', 'frases'),
  ('frase-focus', 'texto'),
  ('frase-focus', 'motivacion'),
  ('frase-focus', 'concentracion'),
  ('frase-focus', 'enfoque'),
  ('frase-focus-glitch', 'frase'),
  ('frase-focus-glitch', 'frases'),
  ('frase-focus-glitch', 'texto'),
  ('frase-focus-glitch', 'motivacion'),
  ('frase-focus-glitch', 'concentracion'),
  ('frase-focus-glitch', 'glitch'),
  ('frase-blah-blah-blah', 'frase'),
  ('frase-blah-blah-blah', 'frases'),
  ('frase-blah-blah-blah', 'texto'),
  ('frase-blah-blah-blah', 'motivacion'),
  ('frase-blah-blah-blah', 'blah'),
  ('frase-blah-blah-blah', 'hablar'),
  ('frase-modo-drama', 'frase'),
  ('frase-modo-drama', 'frases'),
  ('frase-modo-drama', 'texto'),
  ('frase-modo-drama', 'motivacion'),
  ('frase-modo-drama', 'drama'),
  ('frase-modo-drama', 'on'),
  ('frase-cero-interes', 'frase'),
  ('frase-cero-interes', 'frases'),
  ('frase-cero-interes', 'texto'),
  ('frase-cero-interes', 'motivacion'),
  ('frase-cero-interes', 'interes'),
  ('frase-cero-interes', 'aburrido'),
  ('frase-sin-estres', 'frase'),
  ('frase-sin-estres', 'frases'),
  ('frase-sin-estres', 'texto'),
  ('frase-sin-estres', 'motivacion'),
  ('frase-sin-estres', 'estres'),
  ('frase-sin-estres', 'calma'),
  ('frase-solo-se-que-no-se-nada', 'frase'),
  ('frase-solo-se-que-no-se-nada', 'frases'),
  ('frase-solo-se-que-no-se-nada', 'texto'),
  ('frase-solo-se-que-no-se-nada', 'motivacion'),
  ('frase-solo-se-que-no-se-nada', 'socrates'),
  ('frase-solo-se-que-no-se-nada', 'filosofia'),
  ('frase-exceso-de-marketing', 'frase'),
  ('frase-exceso-de-marketing', 'frases'),
  ('frase-exceso-de-marketing', 'texto'),
  ('frase-exceso-de-marketing', 'motivacion'),
  ('frase-exceso-de-marketing', 'marketing'),
  ('frase-exceso-de-marketing', 'publicidad'),
  ('frase-alto-contenido-de-fe', 'frase'),
  ('frase-alto-contenido-de-fe', 'frases'),
  ('frase-alto-contenido-de-fe', 'texto'),
  ('frase-alto-contenido-de-fe', 'motivacion'),
  ('frase-alto-contenido-de-fe', 'fe'),
  ('frase-alto-contenido-de-fe', 'esperanza'),
  ('dev-docker', 'dev'),
  ('dev-docker', 'code'),
  ('dev-docker', 'programacion'),
  ('dev-docker', 'developer'),
  ('dev-docker', 'coding'),
  ('dev-docker', 'tech'),
  ('dev-docker', 'codigo'),
  ('dev-docker', 'docker'),
  ('dev-docker', 'contenedor'),
  ('dev-docker', 'devops'),
  ('dev-typescript', 'dev'),
  ('dev-typescript', 'code'),
  ('dev-typescript', 'programacion'),
  ('dev-typescript', 'developer'),
  ('dev-typescript', 'coding'),
  ('dev-typescript', 'tech'),
  ('dev-typescript', 'codigo'),
  ('dev-typescript', 'typescript'),
  ('dev-typescript', 'ts'),
  ('dev-typescript', 'javascript'),
  ('dev-postman', 'dev'),
  ('dev-postman', 'code'),
  ('dev-postman', 'programacion'),
  ('dev-postman', 'developer'),
  ('dev-postman', 'coding'),
  ('dev-postman', 'tech'),
  ('dev-postman', 'codigo'),
  ('dev-postman', 'postman'),
  ('dev-postman', 'api'),
  ('dev-postman', 'rest'),
  ('dev-inteligencia-artificial', 'dev'),
  ('dev-inteligencia-artificial', 'code'),
  ('dev-inteligencia-artificial', 'programacion'),
  ('dev-inteligencia-artificial', 'developer'),
  ('dev-inteligencia-artificial', 'coding'),
  ('dev-inteligencia-artificial', 'tech'),
  ('dev-inteligencia-artificial', 'codigo'),
  ('dev-inteligencia-artificial', 'ia'),
  ('dev-inteligencia-artificial', 'ai'),
  ('dev-inteligencia-artificial', 'machine learning'),
  ('dev-panic-tabla-periodica', 'dev'),
  ('dev-panic-tabla-periodica', 'code'),
  ('dev-panic-tabla-periodica', 'programacion'),
  ('dev-panic-tabla-periodica', 'developer'),
  ('dev-panic-tabla-periodica', 'coding'),
  ('dev-panic-tabla-periodica', 'tech'),
  ('dev-panic-tabla-periodica', 'codigo'),
  ('dev-panic-tabla-periodica', 'panic'),
  ('dev-panic-tabla-periodica', 'quimica'),
  ('dev-panic-tabla-periodica', 'bug'),
  ('dev-sello-success', 'dev'),
  ('dev-sello-success', 'code'),
  ('dev-sello-success', 'programacion'),
  ('dev-sello-success', 'developer'),
  ('dev-sello-success', 'coding'),
  ('dev-sello-success', 'tech'),
  ('dev-sello-success', 'codigo'),
  ('dev-sello-success', 'success'),
  ('dev-sello-success', 'exito'),
  ('dev-sello-success', 'deploy'),
  ('dev-need-coffee', 'dev'),
  ('dev-need-coffee', 'code'),
  ('dev-need-coffee', 'programacion'),
  ('dev-need-coffee', 'developer'),
  ('dev-need-coffee', 'coding'),
  ('dev-need-coffee', 'tech'),
  ('dev-need-coffee', 'codigo'),
  ('dev-need-coffee', 'cafe'),
  ('dev-need-coffee', 'coffee'),
  ('dev-need-coffee', 'energia'),
  ('dev-espresso-patronum', 'dev'),
  ('dev-espresso-patronum', 'code'),
  ('dev-espresso-patronum', 'programacion'),
  ('dev-espresso-patronum', 'developer'),
  ('dev-espresso-patronum', 'coding'),
  ('dev-espresso-patronum', 'tech'),
  ('dev-espresso-patronum', 'codigo'),
  ('dev-espresso-patronum', 'cafe'),
  ('dev-espresso-patronum', 'espresso'),
  ('dev-espresso-patronum', 'harry potter'),
  ('dev-tecla-esc', 'dev'),
  ('dev-tecla-esc', 'code'),
  ('dev-tecla-esc', 'programacion'),
  ('dev-tecla-esc', 'developer'),
  ('dev-tecla-esc', 'coding'),
  ('dev-tecla-esc', 'tech'),
  ('dev-tecla-esc', 'codigo'),
  ('dev-tecla-esc', 'esc'),
  ('dev-tecla-esc', 'teclado'),
  ('dev-tecla-esc', 'escape'),
  ('dev-laptop-too-cute', 'dev'),
  ('dev-laptop-too-cute', 'code'),
  ('dev-laptop-too-cute', 'programacion'),
  ('dev-laptop-too-cute', 'developer'),
  ('dev-laptop-too-cute', 'coding'),
  ('dev-laptop-too-cute', 'tech'),
  ('dev-laptop-too-cute', 'codigo'),
  ('dev-laptop-too-cute', 'laptop'),
  ('dev-laptop-too-cute', 'compu'),
  ('dev-carpeta-pixel', 'dev'),
  ('dev-carpeta-pixel', 'code'),
  ('dev-carpeta-pixel', 'programacion'),
  ('dev-carpeta-pixel', 'developer'),
  ('dev-carpeta-pixel', 'coding'),
  ('dev-carpeta-pixel', 'tech'),
  ('dev-carpeta-pixel', 'codigo'),
  ('dev-carpeta-pixel', 'carpeta'),
  ('dev-carpeta-pixel', 'pixel'),
  ('dev-carpeta-pixel', 'archivos'),
  ('dev-papelera-pixel', 'dev'),
  ('dev-papelera-pixel', 'code'),
  ('dev-papelera-pixel', 'programacion'),
  ('dev-papelera-pixel', 'developer'),
  ('dev-papelera-pixel', 'coding'),
  ('dev-papelera-pixel', 'tech'),
  ('dev-papelera-pixel', 'codigo'),
  ('dev-papelera-pixel', 'papelera'),
  ('dev-papelera-pixel', 'pixel'),
  ('dev-papelera-pixel', 'basura'),
  ('dev-nube-binaria', 'dev'),
  ('dev-nube-binaria', 'code'),
  ('dev-nube-binaria', 'programacion'),
  ('dev-nube-binaria', 'developer'),
  ('dev-nube-binaria', 'coding'),
  ('dev-nube-binaria', 'tech'),
  ('dev-nube-binaria', 'codigo'),
  ('dev-nube-binaria', 'nube'),
  ('dev-nube-binaria', 'cloud'),
  ('dev-nube-binaria', 'binario'),
  ('dev-loading-retro', 'dev'),
  ('dev-loading-retro', 'code'),
  ('dev-loading-retro', 'programacion'),
  ('dev-loading-retro', 'developer'),
  ('dev-loading-retro', 'coding'),
  ('dev-loading-retro', 'tech'),
  ('dev-loading-retro', 'codigo'),
  ('dev-loading-retro', 'loading'),
  ('dev-loading-retro', 'retro'),
  ('dev-loading-retro', 'cargando'),
  ('dev-pinguinos-loading', 'dev'),
  ('dev-pinguinos-loading', 'code'),
  ('dev-pinguinos-loading', 'programacion'),
  ('dev-pinguinos-loading', 'developer'),
  ('dev-pinguinos-loading', 'coding'),
  ('dev-pinguinos-loading', 'tech'),
  ('dev-pinguinos-loading', 'codigo'),
  ('dev-pinguinos-loading', 'pinguino'),
  ('dev-pinguinos-loading', 'linux'),
  ('dev-pinguinos-loading', 'loading'),
  ('meme-bateria-100', 'meme'),
  ('meme-bateria-100', 'memes'),
  ('meme-bateria-100', 'random'),
  ('meme-bateria-100', 'bateria'),
  ('meme-bateria-100', 'energia'),
  ('meme-bateria-100', 'full'),
  ('meme-bateria-60', 'meme'),
  ('meme-bateria-60', 'memes'),
  ('meme-bateria-60', 'random'),
  ('meme-bateria-60', 'bateria'),
  ('meme-bateria-60', 'energia'),
  ('meme-bateria-40', 'meme'),
  ('meme-bateria-40', 'memes'),
  ('meme-bateria-40', 'random'),
  ('meme-bateria-40', 'bateria'),
  ('meme-bateria-40', 'energia'),
  ('meme-bateria-20', 'meme'),
  ('meme-bateria-20', 'memes'),
  ('meme-bateria-20', 'random'),
  ('meme-bateria-20', 'bateria'),
  ('meme-bateria-20', 'baja'),
  ('meme-bateria-20', 'energia'),
  ('meme-carita-feliz', 'meme'),
  ('meme-carita-feliz', 'memes'),
  ('meme-carita-feliz', 'random'),
  ('meme-carita-feliz', 'feliz'),
  ('meme-carita-feliz', 'smiley'),
  ('meme-carita-feliz', 'sonrisa'),
  ('meme-seis-siete', 'meme'),
  ('meme-seis-siete', 'memes'),
  ('meme-seis-siete', 'random'),
  ('meme-seis-siete', '67'),
  ('meme-seis-siete', 'seis siete'),
  ('meme-seis-siete', 'tendencia'),
  ('meme-tea-rex', 'meme'),
  ('meme-tea-rex', 'memes'),
  ('meme-tea-rex', 'random'),
  ('meme-tea-rex', 'dino'),
  ('meme-tea-rex', 'te'),
  ('meme-tea-rex', 'tea'),
  ('meme-tea-rex', 'dinosaurio'),
  ('meme-flork-musica', 'meme'),
  ('meme-flork-musica', 'memes'),
  ('meme-flork-musica', 'random'),
  ('meme-flork-musica', 'flork'),
  ('meme-flork-musica', 'musica'),
  ('meme-flork-musica', 'audifonos'),
  ('meme-flork-acostado', 'meme'),
  ('meme-flork-acostado', 'memes'),
  ('meme-flork-acostado', 'random'),
  ('meme-flork-acostado', 'flork'),
  ('meme-flork-acostado', 'cansado'),
  ('meme-flork-acostado', 'descanso'),
  ('dev-angular', 'dev'),
  ('dev-angular', 'code'),
  ('dev-angular', 'programacion'),
  ('dev-angular', 'developer'),
  ('dev-angular', 'coding'),
  ('dev-angular', 'tech'),
  ('dev-angular', 'codigo'),
  ('dev-angular', 'logo'),
  ('dev-angular', 'angular'),
  ('dev-angular', 'frontend'),
  ('dev-angular', 'framework'),
  ('dev-aws', 'dev'),
  ('dev-aws', 'code'),
  ('dev-aws', 'programacion'),
  ('dev-aws', 'developer'),
  ('dev-aws', 'coding'),
  ('dev-aws', 'tech'),
  ('dev-aws', 'codigo'),
  ('dev-aws', 'logo'),
  ('dev-aws', 'aws'),
  ('dev-aws', 'amazon'),
  ('dev-aws', 'cloud'),
  ('dev-aws', 'nube'),
  ('dev-aws-lambda', 'dev'),
  ('dev-aws-lambda', 'code'),
  ('dev-aws-lambda', 'programacion'),
  ('dev-aws-lambda', 'developer'),
  ('dev-aws-lambda', 'coding'),
  ('dev-aws-lambda', 'tech'),
  ('dev-aws-lambda', 'codigo'),
  ('dev-aws-lambda', 'logo'),
  ('dev-aws-lambda', 'aws'),
  ('dev-aws-lambda', 'lambda'),
  ('dev-aws-lambda', 'serverless'),
  ('dev-aws-lambda', 'cloud'),
  ('dev-aws-lambda-icono', 'dev'),
  ('dev-aws-lambda-icono', 'code'),
  ('dev-aws-lambda-icono', 'programacion'),
  ('dev-aws-lambda-icono', 'developer'),
  ('dev-aws-lambda-icono', 'coding'),
  ('dev-aws-lambda-icono', 'tech'),
  ('dev-aws-lambda-icono', 'codigo'),
  ('dev-aws-lambda-icono', 'logo'),
  ('dev-aws-lambda-icono', 'aws'),
  ('dev-aws-lambda-icono', 'lambda'),
  ('dev-aws-lambda-icono', 'serverless'),
  ('dev-azure', 'dev'),
  ('dev-azure', 'code'),
  ('dev-azure', 'programacion'),
  ('dev-azure', 'developer'),
  ('dev-azure', 'coding'),
  ('dev-azure', 'tech'),
  ('dev-azure', 'codigo'),
  ('dev-azure', 'logo'),
  ('dev-azure', 'azure'),
  ('dev-azure', 'microsoft'),
  ('dev-azure', 'cloud'),
  ('dev-azure', 'nube'),
  ('dev-azure-texto', 'dev'),
  ('dev-azure-texto', 'code'),
  ('dev-azure-texto', 'programacion'),
  ('dev-azure-texto', 'developer'),
  ('dev-azure-texto', 'coding'),
  ('dev-azure-texto', 'tech'),
  ('dev-azure-texto', 'codigo'),
  ('dev-azure-texto', 'logo'),
  ('dev-azure-texto', 'azure'),
  ('dev-azure-texto', 'microsoft'),
  ('dev-azure-texto', 'cloud'),
  ('dev-chatgpt', 'dev'),
  ('dev-chatgpt', 'code'),
  ('dev-chatgpt', 'programacion'),
  ('dev-chatgpt', 'developer'),
  ('dev-chatgpt', 'coding'),
  ('dev-chatgpt', 'tech'),
  ('dev-chatgpt', 'codigo'),
  ('dev-chatgpt', 'logo'),
  ('dev-chatgpt', 'chatgpt'),
  ('dev-chatgpt', 'openai'),
  ('dev-chatgpt', 'ia'),
  ('dev-chatgpt', 'ai'),
  ('dev-openai', 'dev'),
  ('dev-openai', 'code'),
  ('dev-openai', 'programacion'),
  ('dev-openai', 'developer'),
  ('dev-openai', 'coding'),
  ('dev-openai', 'tech'),
  ('dev-openai', 'codigo'),
  ('dev-openai', 'logo'),
  ('dev-openai', 'openai'),
  ('dev-openai', 'ia'),
  ('dev-openai', 'ai'),
  ('dev-openai', 'gpt'),
  ('dev-copilot', 'dev'),
  ('dev-copilot', 'code'),
  ('dev-copilot', 'programacion'),
  ('dev-copilot', 'developer'),
  ('dev-copilot', 'coding'),
  ('dev-copilot', 'tech'),
  ('dev-copilot', 'codigo'),
  ('dev-copilot', 'logo'),
  ('dev-copilot', 'copilot'),
  ('dev-copilot', 'microsoft'),
  ('dev-copilot', 'ia'),
  ('dev-copilot', 'ai'),
  ('dev-discord', 'dev'),
  ('dev-discord', 'code'),
  ('dev-discord', 'programacion'),
  ('dev-discord', 'developer'),
  ('dev-discord', 'coding'),
  ('dev-discord', 'tech'),
  ('dev-discord', 'codigo'),
  ('dev-discord', 'logo'),
  ('dev-discord', 'discord'),
  ('dev-discord', 'chat'),
  ('dev-discord', 'comunidad'),
  ('dev-discord-texto', 'dev'),
  ('dev-discord-texto', 'code'),
  ('dev-discord-texto', 'programacion'),
  ('dev-discord-texto', 'developer'),
  ('dev-discord-texto', 'coding'),
  ('dev-discord-texto', 'tech'),
  ('dev-discord-texto', 'codigo'),
  ('dev-discord-texto', 'logo'),
  ('dev-discord-texto', 'discord'),
  ('dev-discord-texto', 'chat'),
  ('dev-duolingo', 'dev'),
  ('dev-duolingo', 'code'),
  ('dev-duolingo', 'programacion'),
  ('dev-duolingo', 'developer'),
  ('dev-duolingo', 'coding'),
  ('dev-duolingo', 'tech'),
  ('dev-duolingo', 'codigo'),
  ('dev-duolingo', 'logo'),
  ('dev-duolingo', 'duolingo'),
  ('dev-duolingo', 'idiomas'),
  ('dev-duolingo', 'buho'),
  ('dev-git', 'dev'),
  ('dev-git', 'code'),
  ('dev-git', 'programacion'),
  ('dev-git', 'developer'),
  ('dev-git', 'coding'),
  ('dev-git', 'tech'),
  ('dev-git', 'codigo'),
  ('dev-git', 'logo'),
  ('dev-git', 'git'),
  ('dev-git', 'control de versiones'),
  ('dev-git', 'vcs'),
  ('dev-git-bash', 'dev'),
  ('dev-git-bash', 'code'),
  ('dev-git-bash', 'programacion'),
  ('dev-git-bash', 'developer'),
  ('dev-git-bash', 'coding'),
  ('dev-git-bash', 'tech'),
  ('dev-git-bash', 'codigo'),
  ('dev-git-bash', 'logo'),
  ('dev-git-bash', 'git'),
  ('dev-git-bash', 'bash'),
  ('dev-git-bash', 'terminal'),
  ('dev-git-bash', 'consola'),
  ('dev-github-texto', 'dev'),
  ('dev-github-texto', 'code'),
  ('dev-github-texto', 'programacion'),
  ('dev-github-texto', 'developer'),
  ('dev-github-texto', 'coding'),
  ('dev-github-texto', 'tech'),
  ('dev-github-texto', 'codigo'),
  ('dev-github-texto', 'logo'),
  ('dev-github-texto', 'github'),
  ('dev-github-texto', 'git'),
  ('dev-github-texto', 'repo'),
  ('dev-github-completo', 'dev'),
  ('dev-github-completo', 'code'),
  ('dev-github-completo', 'programacion'),
  ('dev-github-completo', 'developer'),
  ('dev-github-completo', 'coding'),
  ('dev-github-completo', 'tech'),
  ('dev-github-completo', 'codigo'),
  ('dev-github-completo', 'logo'),
  ('dev-github-completo', 'github'),
  ('dev-github-completo', 'git'),
  ('dev-github-completo', 'repo'),
  ('dev-github-completo', 'octocat'),
  ('dev-github-icono', 'dev'),
  ('dev-github-icono', 'code'),
  ('dev-github-icono', 'programacion'),
  ('dev-github-icono', 'developer'),
  ('dev-github-icono', 'coding'),
  ('dev-github-icono', 'tech'),
  ('dev-github-icono', 'codigo'),
  ('dev-github-icono', 'logo'),
  ('dev-github-icono', 'github'),
  ('dev-github-icono', 'git'),
  ('dev-github-icono', 'octocat'),
  ('dev-gitlab-texto', 'dev'),
  ('dev-gitlab-texto', 'code'),
  ('dev-gitlab-texto', 'programacion'),
  ('dev-gitlab-texto', 'developer'),
  ('dev-gitlab-texto', 'coding'),
  ('dev-gitlab-texto', 'tech'),
  ('dev-gitlab-texto', 'codigo'),
  ('dev-gitlab-texto', 'logo'),
  ('dev-gitlab-texto', 'gitlab'),
  ('dev-gitlab-texto', 'git'),
  ('dev-gitlab-texto', 'repo'),
  ('dev-gitlab', 'dev'),
  ('dev-gitlab', 'code'),
  ('dev-gitlab', 'programacion'),
  ('dev-gitlab', 'developer'),
  ('dev-gitlab', 'coding'),
  ('dev-gitlab', 'tech'),
  ('dev-gitlab', 'codigo'),
  ('dev-gitlab', 'logo'),
  ('dev-gitlab', 'gitlab'),
  ('dev-gitlab', 'git'),
  ('dev-gitlab', 'repo'),
  ('dev-gitlab', 'zorro'),
  ('dev-gitlab-wordmark', 'dev'),
  ('dev-gitlab-wordmark', 'code'),
  ('dev-gitlab-wordmark', 'programacion'),
  ('dev-gitlab-wordmark', 'developer'),
  ('dev-gitlab-wordmark', 'coding'),
  ('dev-gitlab-wordmark', 'tech'),
  ('dev-gitlab-wordmark', 'codigo'),
  ('dev-gitlab-wordmark', 'logo'),
  ('dev-gitlab-wordmark', 'gitlab'),
  ('dev-gitlab-wordmark', 'git'),
  ('dev-java', 'dev'),
  ('dev-java', 'code'),
  ('dev-java', 'programacion'),
  ('dev-java', 'developer'),
  ('dev-java', 'coding'),
  ('dev-java', 'tech'),
  ('dev-java', 'codigo'),
  ('dev-java', 'logo'),
  ('dev-java', 'java'),
  ('dev-java', 'jvm'),
  ('dev-java', 'backend'),
  ('dev-java', 'cafe'),
  ('dev-java-naranja', 'dev'),
  ('dev-java-naranja', 'code'),
  ('dev-java-naranja', 'programacion'),
  ('dev-java-naranja', 'developer'),
  ('dev-java-naranja', 'coding'),
  ('dev-java-naranja', 'tech'),
  ('dev-java-naranja', 'codigo'),
  ('dev-java-naranja', 'logo'),
  ('dev-java-naranja', 'java'),
  ('dev-java-naranja', 'jvm'),
  ('dev-java-naranja', 'backend'),
  ('dev-java-duke', 'dev'),
  ('dev-java-duke', 'code'),
  ('dev-java-duke', 'programacion'),
  ('dev-java-duke', 'developer'),
  ('dev-java-duke', 'coding'),
  ('dev-java-duke', 'tech'),
  ('dev-java-duke', 'codigo'),
  ('dev-java-duke', 'logo'),
  ('dev-java-duke', 'java'),
  ('dev-java-duke', 'duke'),
  ('dev-java-duke', 'mascota'),
  ('dev-excel', 'dev'),
  ('dev-excel', 'code'),
  ('dev-excel', 'programacion'),
  ('dev-excel', 'developer'),
  ('dev-excel', 'coding'),
  ('dev-excel', 'tech'),
  ('dev-excel', 'codigo'),
  ('dev-excel', 'logo'),
  ('dev-excel', 'excel'),
  ('dev-excel', 'microsoft'),
  ('dev-excel', 'office'),
  ('dev-excel', 'hojas'),
  ('dev-office', 'dev'),
  ('dev-office', 'code'),
  ('dev-office', 'programacion'),
  ('dev-office', 'developer'),
  ('dev-office', 'coding'),
  ('dev-office', 'tech'),
  ('dev-office', 'codigo'),
  ('dev-office', 'logo'),
  ('dev-office', 'office'),
  ('dev-office', 'microsoft'),
  ('dev-office', 'ofimatica'),
  ('dev-powerpoint', 'dev'),
  ('dev-powerpoint', 'code'),
  ('dev-powerpoint', 'programacion'),
  ('dev-powerpoint', 'developer'),
  ('dev-powerpoint', 'coding'),
  ('dev-powerpoint', 'tech'),
  ('dev-powerpoint', 'codigo'),
  ('dev-powerpoint', 'logo'),
  ('dev-powerpoint', 'powerpoint'),
  ('dev-powerpoint', 'microsoft'),
  ('dev-powerpoint', 'office'),
  ('dev-powerpoint', 'ppt'),
  ('dev-teams', 'dev'),
  ('dev-teams', 'code'),
  ('dev-teams', 'programacion'),
  ('dev-teams', 'developer'),
  ('dev-teams', 'coding'),
  ('dev-teams', 'tech'),
  ('dev-teams', 'codigo'),
  ('dev-teams', 'logo'),
  ('dev-teams', 'teams'),
  ('dev-teams', 'microsoft'),
  ('dev-teams', 'chat'),
  ('dev-teams', 'reunion'),
  ('dev-word', 'dev'),
  ('dev-word', 'code'),
  ('dev-word', 'programacion'),
  ('dev-word', 'developer'),
  ('dev-word', 'coding'),
  ('dev-word', 'tech'),
  ('dev-word', 'codigo'),
  ('dev-word', 'logo'),
  ('dev-word', 'word'),
  ('dev-word', 'microsoft'),
  ('dev-word', 'office'),
  ('dev-word', 'documento'),
  ('dev-minecraft', 'dev'),
  ('dev-minecraft', 'code'),
  ('dev-minecraft', 'programacion'),
  ('dev-minecraft', 'developer'),
  ('dev-minecraft', 'coding'),
  ('dev-minecraft', 'tech'),
  ('dev-minecraft', 'codigo'),
  ('dev-minecraft', 'logo'),
  ('dev-minecraft', 'minecraft'),
  ('dev-minecraft', 'juego'),
  ('dev-minecraft', 'pixel'),
  ('dev-minecraft', 'bloques'),
  ('dev-nasa', 'dev'),
  ('dev-nasa', 'code'),
  ('dev-nasa', 'programacion'),
  ('dev-nasa', 'developer'),
  ('dev-nasa', 'coding'),
  ('dev-nasa', 'tech'),
  ('dev-nasa', 'codigo'),
  ('dev-nasa', 'logo'),
  ('dev-nasa', 'nasa'),
  ('dev-nasa', 'espacio'),
  ('dev-nasa', 'ciencia'),
  ('dev-nasa', 'cohete'),
  ('dev-nasa-negro', 'dev'),
  ('dev-nasa-negro', 'code'),
  ('dev-nasa-negro', 'programacion'),
  ('dev-nasa-negro', 'developer'),
  ('dev-nasa-negro', 'coding'),
  ('dev-nasa-negro', 'tech'),
  ('dev-nasa-negro', 'codigo'),
  ('dev-nasa-negro', 'logo'),
  ('dev-nasa-negro', 'nasa'),
  ('dev-nasa-negro', 'espacio'),
  ('dev-nasa-negro', 'ciencia'),
  ('dev-nextjs', 'dev'),
  ('dev-nextjs', 'code'),
  ('dev-nextjs', 'programacion'),
  ('dev-nextjs', 'developer'),
  ('dev-nextjs', 'coding'),
  ('dev-nextjs', 'tech'),
  ('dev-nextjs', 'codigo'),
  ('dev-nextjs', 'logo'),
  ('dev-nextjs', 'nextjs'),
  ('dev-nextjs', 'react'),
  ('dev-nextjs', 'frontend'),
  ('dev-nextjs', 'framework'),
  ('dev-nextjs-cubo', 'dev'),
  ('dev-nextjs-cubo', 'code'),
  ('dev-nextjs-cubo', 'programacion'),
  ('dev-nextjs-cubo', 'developer'),
  ('dev-nextjs-cubo', 'coding'),
  ('dev-nextjs-cubo', 'tech'),
  ('dev-nextjs-cubo', 'codigo'),
  ('dev-nextjs-cubo', 'logo'),
  ('dev-nextjs-cubo', 'next'),
  ('dev-nextjs-cubo', 'nextjs'),
  ('dev-nextjs-cubo', 'retro'),
  ('dev-npm', 'dev'),
  ('dev-npm', 'code'),
  ('dev-npm', 'programacion'),
  ('dev-npm', 'developer'),
  ('dev-npm', 'coding'),
  ('dev-npm', 'tech'),
  ('dev-npm', 'codigo'),
  ('dev-npm', 'logo'),
  ('dev-npm', 'npm'),
  ('dev-npm', 'node'),
  ('dev-npm', 'paquetes'),
  ('dev-npm', 'javascript'),
  ('dev-npm-cubo', 'dev'),
  ('dev-npm-cubo', 'code'),
  ('dev-npm-cubo', 'programacion'),
  ('dev-npm-cubo', 'developer'),
  ('dev-npm-cubo', 'coding'),
  ('dev-npm-cubo', 'tech'),
  ('dev-npm-cubo', 'codigo'),
  ('dev-npm-cubo', 'logo'),
  ('dev-npm-cubo', 'npm'),
  ('dev-npm-cubo', 'node'),
  ('dev-npm-cubo', 'paquetes'),
  ('dev-npm-cuadrado', 'dev'),
  ('dev-npm-cuadrado', 'code'),
  ('dev-npm-cuadrado', 'programacion'),
  ('dev-npm-cuadrado', 'developer'),
  ('dev-npm-cuadrado', 'coding'),
  ('dev-npm-cuadrado', 'tech'),
  ('dev-npm-cuadrado', 'codigo'),
  ('dev-npm-cuadrado', 'logo'),
  ('dev-npm-cuadrado', 'npm'),
  ('dev-npm-cuadrado', 'node'),
  ('dev-npm-cuadrado', 'paquetes'),
  ('dev-nvidia', 'dev'),
  ('dev-nvidia', 'code'),
  ('dev-nvidia', 'programacion'),
  ('dev-nvidia', 'developer'),
  ('dev-nvidia', 'coding'),
  ('dev-nvidia', 'tech'),
  ('dev-nvidia', 'codigo'),
  ('dev-nvidia', 'logo'),
  ('dev-nvidia', 'nvidia'),
  ('dev-nvidia', 'gpu'),
  ('dev-nvidia', 'gráfica'),
  ('dev-nvidia', 'hardware'),
  ('dev-python', 'dev'),
  ('dev-python', 'code'),
  ('dev-python', 'programacion'),
  ('dev-python', 'developer'),
  ('dev-python', 'coding'),
  ('dev-python', 'tech'),
  ('dev-python', 'codigo'),
  ('dev-python', 'logo'),
  ('dev-python', 'python'),
  ('dev-python', 'backend'),
  ('dev-python', 'script'),
  ('dev-python', 'serpiente'),
  ('dev-python-texto', 'dev'),
  ('dev-python-texto', 'code'),
  ('dev-python-texto', 'programacion'),
  ('dev-python-texto', 'developer'),
  ('dev-python-texto', 'coding'),
  ('dev-python-texto', 'tech'),
  ('dev-python-texto', 'codigo'),
  ('dev-python-texto', 'logo'),
  ('dev-python-texto', 'python'),
  ('dev-python-texto', 'backend'),
  ('dev-python-texto', 'script'),
  ('dev-python-icono', 'dev'),
  ('dev-python-icono', 'code'),
  ('dev-python-icono', 'programacion'),
  ('dev-python-icono', 'developer'),
  ('dev-python-icono', 'coding'),
  ('dev-python-icono', 'tech'),
  ('dev-python-icono', 'codigo'),
  ('dev-python-icono', 'logo'),
  ('dev-python-icono', 'python'),
  ('dev-python-icono', 'backend'),
  ('dev-python-icono', 'script'),
  ('dev-pypi', 'dev'),
  ('dev-pypi', 'code'),
  ('dev-pypi', 'programacion'),
  ('dev-pypi', 'developer'),
  ('dev-pypi', 'coding'),
  ('dev-pypi', 'tech'),
  ('dev-pypi', 'codigo'),
  ('dev-pypi', 'logo'),
  ('dev-pypi', 'pypi'),
  ('dev-pypi', 'python'),
  ('dev-pypi', 'paquetes'),
  ('dev-pypi', 'pip'),
  ('dev-slack', 'dev'),
  ('dev-slack', 'code'),
  ('dev-slack', 'programacion'),
  ('dev-slack', 'developer'),
  ('dev-slack', 'coding'),
  ('dev-slack', 'tech'),
  ('dev-slack', 'codigo'),
  ('dev-slack', 'logo'),
  ('dev-slack', 'slack'),
  ('dev-slack', 'chat'),
  ('dev-slack', 'trabajo'),
  ('dev-slack', 'equipo'),
  ('dev-slack-icono', 'dev'),
  ('dev-slack-icono', 'code'),
  ('dev-slack-icono', 'programacion'),
  ('dev-slack-icono', 'developer'),
  ('dev-slack-icono', 'coding'),
  ('dev-slack-icono', 'tech'),
  ('dev-slack-icono', 'codigo'),
  ('dev-slack-icono', 'logo'),
  ('dev-slack-icono', 'slack'),
  ('dev-slack-icono', 'chat'),
  ('dev-slack-icono', 'equipo')
) as v(sticker_slug, tag_slug)
join public.stickers s on s.slug = v.sticker_slug
join public.tags t on t.slug = v.tag_slug
on conflict do nothing;

insert into public.packs (slug, badge_label, name, description, image_url, price, sort_order) values
  ('pack-fortnite', 'Gaming', 'Pack Fortnite', '10 sprites de Fortnite en vinil resistente al agua. Mítico, legendario, épico y más.', '/img/packs/pack-fortnite.webp', 8.5, 0),
  ('pack-developer', 'Tech', 'Pack Developer', '10 stickers de lenguajes, herramientas y logos dev para tu laptop.', '/img/packs/pack-developers.webp', 8.5, 1),
  ('pack-gatos', 'Memes', 'Pack Gatos', '10 gatos meme para tu setup. Selección de la casa.', '/img/packs/pack-gatos.webp', 8.5, 2)
on conflict (slug) do update set
  badge_label = excluded.badge_label, name = excluded.name, description = excluded.description,
  image_url = excluded.image_url, price = excluded.price, sort_order = excluded.sort_order;
